### ISSUE TITLE
Spurious "INFO: " message during restore

### ISSUE THREAD

**Issue by amitlan** [ossc-db/pg_rman#1]
When I try to restore to a too old timeline (that is, no full backup on that timeline was ever taken), pg_rman restore rightly complains; but some stderr messages go out too soon:

```
$ pg_rman restore --recovery-target-timeline=1
INFO: copying online WAL files and server log files
ERROR: no full backup is found.
```

After inspecting in do_restore(), it seems backup_online_files() is called too soon. That is, before it is determined that a good enough backup exists. I remember we had fixed restore-destination-clear-too-soon bug months ago. Now, this is different but seems a thing reasonable to do. That is, do backup_online_files() after we've found a valid base backup.

**Comment by bwtakacy** [comment]
Thanks!

I merge the pull-request about this issue.

**Comment by amitlan** [comment]
Thank you!

Does this need to be backpatched? I know INFO messages are only in HEAD (and a reason for this issue) but anything that backup_online_files() does should better be done after finding useful backup anyway. So what do you think?

**Comment by bwtakacy** [comment]
Yeah.

I did back-patched this for all other branches.
