### ISSUE TITLE
Cannot install pg_rman on Ubuntu 18.0.4

### ISSUE THREAD

**Issue by jackeylhm** [ossc-db/pg_rman#107]
Can pg_rman be installed in Ubuntu 18.0.4? As when I compiled it using "make", I got the following error:

/usr/bin/ld: cannot find -lselinux
/usr/bin/ld: cannot find -lpam
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lgssapi_krb5
/usr/bin/ld: cannot find -ledit

I tried to fix these errors but it was messy and unsuccessful.

**Comment by ruben-farma** [comment]
I have the same issue on debian stretch 9.9

**Comment by ruben-farma** [comment]
It's possible to compile a .deb files?

**Comment by NelsonFrancisco** [comment]
same happens with postgres-10 docker image
Dockerfile:
```
FROM postgres-10

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get update
RUN apt-get install -y zlib1g-dev

RUN mkdir /tmp/pg_rman
ADD pg_rman-REL_10_STABLE /tmp/pg_rman
WORKDIR /tmp/pg_rman/
RUN make 
RUN make install
RUN rm -rf /tmp/pg_rman
```

**Comment by jackeylhm** [comment]
@NelsonFrancisco 
Installing those libraries does solve my problem. Fantastic, this ought to be part of pg_rman 's installation instruction.
Millions of thanks!
