### ISSUE TITLE
Is pg_rman able to be installed on Solaris?

### ISSUE THREAD

**Issue by jingmamour** [ossc-db/pg_rman#108]
Hello,I try to install pg_rman on solaris but I failed.I downloaded the source code from master branch and try to make，it show make error :In line 35:Unexpect end of line seen.Then  I tried use gmake ,it show too many  errors.

Does pg_rman support to be installed on Solaris?

**Comment by MoonInsung** [comment]
Dear jingmamour.

Sorry, pg_rman is no guarantee whether it runs on Solaris.
pg_rman works based on RHEL according to the manual.
Even if the installation is successful on Solaris, there is no guarantee that it will work properly.

Best regards.
Moon.
