### ISSUE TITLE
User-manual modification is required.

### ISSUE THREAD

**Issue by MoonInsung** [ossc-db/pg_rman#110]
Incorrect recovery time setting for items in the manual Delete backups part. (English version, Japanese version)
It is a need for modification to the correct time (2015-07-30 13:30:30).

And a need to modify the manual for version information.

**Comment by amitlan** [comment]
Moon-san,  thanks for the report.

PR #111 fixes this.  That PR can be merged into older branches (up to 11), but not master branch yet, because we haven't fixed the build issues with v12.  So, let's fix the build with v12 and then merge #111 to all branches at the same time.

**Comment by MoonInsung** [comment]
If mount an external directory for some folders in the DBcluster, the files cannot be deleted due to OS policy(maybe..).
Therefore, when execute recovering, it is not working properly.
We will need to update these constraints(mount directory) to the pg_rman user manual.

**Comment by MoonInsung** [comment]
Additions
-----------
Add information of the "force", which is the backup file deletion option to the pg_rman manual.
Besides, it is necessary to add some caution when using the "force" option.
