### ISSUE TITLE
restore failed with "ERROR: could not read block 0 ..."

### ISSUE THREAD

**Issue by tangweichun** [ossc-db/pg_rman#117]
Hi,

#pg_rman show
=====================================================================
 StartTime           EndTime              Mode    Size   TLI  Status 
=====================================================================
2019-09-28 15:53:05  2019-09-28 15:53:32  FULL    67MB     1  OK
2019-09-28 00:00:02  2019-09-28 00:01:15  FULL    88MB     1  OK
2019-09-27 00:00:01  2019-09-27 00:01:16  FULL    86MB     1  OK
2019-09-26 00:00:01  2019-09-26 00:01:12  FULL    87MB     1  OK
2019-09-25 00:00:01  2019-09-25 00:01:15  FULL    89MB     1  OK
2019-09-24 00:00:02  2019-09-24 00:01:15  FULL    85MB     1  OK
2019-09-23 00:00:01  2019-09-23 00:01:13  FULL    87MB     1  OK
2019-09-22 00:00:01  2019-09-22 00:01:29  FULL    87MB     1  OK
2019-09-21 00:00:01  2019-09-21 00:01:25  FULL    87MB     1  OK

#pg_rman restore -D /path/to/dest --recovery-target-time '2019-09-28 00:00:02'
WARNING: pg_controldata file "/path/to/pg_control" does not exist
INFO: the recovery target timeline ID is not given
INFO: use timeline ID of latest full backup as recovery target: 1
INFO: calculating timeline branches to be used to recovery target point
INFO: searching latest full backup which can be used as restore start point
INFO: found the full backup can be used as base in recovery: "2019-09-27 00:00:01"
INFO: copying online WAL files and server log files
INFO: clearing restore destination
INFO: validate: "2019-09-27 00:00:01" backup and archive log files by SIZE
INFO: backup "2019-09-27 00:00:01" is valid
INFO: restoring database files from the full mode backup "2019-09-27 00:00:01"
ERROR: could not read block 0 of "/path/to/20190927/000001/database/base/1/1247_vm"

**Comment by MoonInsung** [comment]
Hello.
Look only at the error message, it is occurs problem by the impossible to read the backup files.
Maybe a physical error in the file..
If it's not a physical error, do you know how to reproduce this problem?

**Comment by MoonInsung** [comment]
Dear @tangweichun 

I apologize for this comment. 
This issue is very old, so if you don't have any opinion, 
I'll close the issue around June 28th(JST).
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
