### ISSUE TITLE
Tweak Travis-CI notification config in master branch

### ISSUE THREAD

**Issue by amitlan** [ossc-db/pg_rman#12]
I have received about 10 email notifications so far, titled "Fixed: ossc-db/pg_rman#138 (master - 8e6e833)" since Nov 6. That is, build #138 (on Travis-CI) sends a notification every time it runs, even if its status does not change. That is a bit annoying.

I read that there is following configuration to fix it:

```
notifications:
  email:
    on_success: change
```

That is, notify only when the status of a build changes. Is that right? If so, Should we add that to .travis.yml of the master branch? Regarding other branches, I guess we don't expect a build for those branches to run more than once (on a commit to the branch only). But then can someone tell me why build #138 ran multiple times?

**Comment by bwtakacy** [comment]
Sorry, I did run latest commit of master branch almost every day.
This is to check whether the updates of postgres breaks pg_rman regression tests.

Although I have received such mails too, but I did not use it as usuful infomation.
How about disabling email notification?

```
notifications:
  email: false
```

**Comment by bwtakacy** [comment]
Hmm, there seems a way to send email only for specified address.

```
notifications:
  email:
    - one@example.com
    - other@example.com
```

**Comment by amitlan** [comment]
Do you mean, -  you manually ran the build #138 by pushing "Restart build" button?

**Comment by bwtakacy** [comment]
Yes.

**Comment by amitlan** [comment]
Oh, I understand then.

We need to do something about the email notification. Disabling it altogether is is an option like you suggested. But if such a build fails, others could learn about the failure if notified. That is, if a build fails due to changes unrelated to pg_rman (master) like some upstream change, then it would be nice to let interested parties know. By default, the committer and author of the latest commit are notified. I read it [here](https://docs.travis-ci.com/user/notifications/#How-is-the-build-email-receiver-determined%3F).

Thought?

**Comment by amitlan** [comment]
Just noticed that if I restart a build for pg_bulkload (say, [build #11](https://travis-ci.org/ossc-db/pg_bulkload/builds/73990246)), the same notification email wasn't sent. Both pg_bulkload and pg_rman repos use very similar `.travis.yml`. Also, Travis-CI docs [suggest](https://docs.travis-ci.com/user/notifications/#Email-notifications) the default behavior for notifications is:

```
notifications:
  email:
    on_success: change
    on_failure: always
```

Not sure why notifications in pg_rman's case.

**Comment by bwtakacy** [comment]
Yeah, it is worth to enable to notify about failure.
This seems to be better:)

```
notifications:
  email:
    on_success: change
    on_failure: always
```

About the difference between pg_bulkload and pg_rman.
I'm not sure but Travis CI seems send emails about the commit whose first test trial fails.
And, pg_rman's reggression tests sometimes fails due to memory lackness.

**Comment by bwtakacy** [comment]
I have found you already commited, Amit-san.
Thanks!

**Comment by amitlan** [comment]
Yeah, I committed to see if it works and it seems it does. I did not receive any redundant notifications when I restarted [build #145](https://travis-ci.org/ossc-db/pg_rman/builds/93315130) repeatedly. Though, the mystery remains why we needed to change .travis.yml if that's the default behavior for notifications when not explicitly specified.
