### ISSUE TITLE
latest pg_rman tar.gz for PostgreSQL 10.11 on RHEL/CentOS

### ISSUE THREAD

**Issue by cmodomingo** [ossc-db/pg_rman#131]
Good day!

I'm having trouble installing pg_rman on RHEL with PostgreSQL 10.11 (source installed). Below are the errors i'm getting trying to install via RPM or source:

[pgsql@cvmk0006 pg_rman-REL_10_STABLE]$ cat /proc/version
Linux version 3.10.0-957.27.2.el7.x86_64 (mockbuild@x86-040.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Tue Jul 9 16:53:14 UTC 2019

[pgsql@cvmk0006 pg_rman-REL_10_STABLE]$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -I/pgsql/g01/software/rdbms/10.11.0/include -lm -I. -I./ -I/pgsql/g01/software/rdbms/10.11.0/include/server -I/pgsql/g01/software/rdbms/10.11.0/include/internal  -D_GNU_SOURCE -I/pgsql/g01/software/rdbms/10.11.0/include/libxml2   -c -o data.o data.c
data.c: In function ‘backup_data_file’:
data.c:347:3: warning: implicit declaration of function ‘figure_out_segno’ [-Wimplicit-function-declaration]
   segno = figure_out_segno(file->path);
   ^
data.c: At top level:
data.c:1261:1: error: conflicting types for ‘figure_out_segno’
 figure_out_segno(char *filepath)
 ^
data.c:347:11: note: previous implicit declaration of ‘figure_out_segno’ was here
   segno = figure_out_segno(file->path);
           ^
data.c: In function ‘figure_out_segno’:
data.c:1268:8: warning: variable ‘scanned’ set but not used [-Wunused-but-set-variable]
   int  scanned;
        ^
data.c: At top level:
data.c:1261:1: warning: ‘figure_out_segno’ defined but not used [-Wunused-function]
 figure_out_segno(char *filepath)
 ^
make: *** [data.o] Error 1

[pgsql@cvmk0006 pg_rman-REL_10_STABLE]$ cd ..
[pgsql@cvmk0006 contrib]$ rpm -i pg_rman-1.3.9-1.pg10.rhel7.x86_64.rpm
error: Failed dependencies:
        libpq.so.5()(64bit) is needed by pg_rman-1.3.9-1.pg10.rhel7.x86_64
        postgresql10-libs is needed by pg_rman-1.3.9-1.pg10.rhel7.x86_64_

[pgsql@cvmk0006 contrib]$ psql --version
psql (PostgreSQL) 10.11

[pgsql@cvmk0006 contrib]$ pg_ctl status -D /pgsql/g01/db01/pg10.11/
pg_ctl: server is running (PID: 28383)
/pgsql/g01/software/rdbms/10.11.0/bin/postgres "-D" "/pgsql/g01/db01/pg10.11"

**Comment by huangfumingyue** [comment]
HELLO
You need to use REL_10_STABLE branch of pg_rman to build with Postgres 10 
There is a note in README about this, by the way

**Comment by abdoali786** [comment]
Facing similar issue with postgres 12 on RMAN 12 version.... Can someone pls check and advise... Thanks in advance !!

sh-4.4$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.2 (Ootpa)
sh-4.4$ env | grep LIB
LD_LIBRARY_PATH=/postgres/PGSQL_12.1//lib
sh-4.4$ env | grep HOME
PGHOME=/postgres/PGSQL_12.1/
HOME=/home/postgres
sh-4.4$ psql
psql (12.1)
Type "help" for help.

postgres=# exit
sh-4.4$ tmake install
sh: tmake: command not found
sh-4.4$ make install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -I/postgres/PGSQL_12.1/include -lm -I. -I./ -I/postgres/PGSQL_12.1/include/server -I/postgres/PGSQL_12.1/include/internal -D_GNU_SOURCE -c -o data.o data.c
data.c: In function ‘backup_data_file’:
data.c:346:11: warning: implicit declaration of function ‘figure_out_segno’ [-Wimplicit-function-declaration]
segno = figure_out_segno(file->path);
^~~~~~~~~~~~~~~~
data.c: At top level:
data.c:1260:1: error: conflicting types for ‘figure_out_segno’
figure_out_segno(char *filepath)
^~~~~~~~~~~~~~~~
data.c:346:11: note: previous implicit declaration of ‘figure_out_segno’ was here
segno = figure_out_segno(file->path);
^~~~~~~~~~~~~~~~
data.c: In function ‘figure_out_segno’:
data.c:1267:8: warning: variable ‘scanned’ set but not used [-Wunused-but-set-variable]
int scanned;
^~~~~~~
At top level:
data.c:1260:1: warning: ‘figure_out_segno’ defined but not used [-Wunused-function]
figure_out_segno(char *filepath)
^~~~~~~~~~~~~~~~
make: *** [: data.o] Error 1

**Comment by MoonInsung** [comment]
Dear @cmodomingo 

Is it possible to check again using the latest version of the pg_rman?
In the case of the latest version, maybe no build error occurs.

And I apologize for this comment. 
This issue is very old, so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
