### ISSUE TITLE
validation error. log output is "WARNING: CRC calculation showed incorrect result" 

### ISSUE THREAD

**Issue by busitd** [ossc-db/pg_rman#140]
Hi.

Spec:
```
$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)

$ /usr/pgsql-9.5/bin/pg_ctl --version
pg_ctl (PostgreSQL) 9.5.15

$ /usr/pgsql-9.5/bin/pg_rman --version
pg_rman 1.3.8
```

I tried pg_rman full backup but I catched CORRUPT status,

```
$ /usr/pgsql-9.5/bin/pg_rman show -B /{BACKUP_DIR}/
=====================================================================
 StartTime           EndTime              Mode    Size   TLI  Status
=====================================================================
2020-07-04 03:10:03  2020-07-04 03:48:01  FULL   718GB     1  CORRUPT
```

and I catched below log, 
(
"[time] comment" is my own anacron script output. 
INFO... and WARNING... are pg_rman output.

In fact, backup command is 
`sudo -u postgres -i bash -c "/usr/pgsql-9.5/bin/pg_rman backup -D $DATA_DIR -B $BACKUP_DIR -b full --keep-arclog-days 7 >> $backuplog 2>&1"`

:  $DATA_DIR means $PGDATA in my script.

and validate command is 
`sudo -u postgres -i bash -c "/usr/pgsql-9.5/bin/pg_rman validate -B $BACKUP_DIR >> $backuplog 2>&1"`
)
```
[2020-07-04 03:10:03,107] Start pg_rman_backup_full.sh
[2020-07-04 03:10:03,145] processing pg_rman backup -b full --keep-arclog-days 7
INFO: copying database files
INFO: copying archived WAL files
INFO: backup complete
INFO: Please execute 'pg_rman validate' to verify the files are correctly copied.
INFO: start deleting old archived WAL files from ARCLOG_PATH (keep days = 7)
INFO: the threshold timestamp calculated by keep days is "2020-06-27 00:00:00"
INFO: delete "00000001000000CD000000FC"
[2020-07-04 03:48:01,778] processing pg_rman validate
INFO: validate: "2020-07-04 03:10:03" backup and archive log files by CRC
WARNING: CRC calculation showed incorrect result
WARNING: backup "2020-07-04 03:10:03" is corrupted
```

/{BACKUP_DIR}/ is actually Windows Server via SMB3.0 (I used cifs-utils).

I need this database backup.
How could I do?

**Comment by MoonInsung** [comment]
Dear @busitd 

Sorry. I couldn't find a solution to this problem.
The pg_rman was developed to work in the RHEL environment.
Therefore, if the directory being back up is outside of the RHEL, 
it cannot be guaranteed normal operation...

And I apologize for this comment. 
This issue was registered a year ago, 
so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
