### ISSUE TITLE
PG_RMAN in 9.5 error

### ISSUE THREAD

**Issue by ZSH9053** [ossc-db/pg_rman#142]
HINT:  WAL control functions cannot be executed during recovery.
query was: SELECT * FROM pg_xlogfile_name_offset(pg_stop_backup())
ERROR: query failed: ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
query was: SELECT * FROM pg_xlogfile_name_offset(pg_stop_backup())

command ：/usr/pgsql-9.5/bin/pg_rman backup --backup-mode=full --progress -Z --keep-data-days=7 --keep-arclog-days=7 --standby-host=10.41.8.69 --standby-port=5432;

how do I slove this error？

my pg config
data_directory = '/service/databases/postgresql/data'
hba_file = '/service/etc/postgresql/9.5/pg_hba.conf'
ident_file = '/service/etc/postgresql/9.5/pg_ident.conf'
external_pid_file = '/service/databases/postgresql/run/9.5-main.pid'	
listen_addresses = '*'
port = 5432	
max_connections = 5000	
max_prepared_transactions = 5000
superuser_reserved_connections = 20
unix_socket_directories = '/service/databases/postgresql/run'
unix_socket_permissions = 0700

#ssl
ssl = true	
ssl_cert_file = '/service/ssl/pgsql/server.crt'     
ssl_key_file = '/service/ssl/pgsql/server.key'         

tcp_keepalives_idle = 30               
tcp_keepalives_interval = 10
tcp_keepalives_count = 10
shared_buffers = 16GB
#huge_pages = try           
autovacuum_work_mem = 128MB
bgwriter_delay = 10ms
bgwriter_lru_maxpages = 1000
max_worker_processes = 20 
wal_level = hot_standby                    
synchronous_commit = local
archive_mode = on
archive_command = 'cp -i %p /service/databases/postgresql/archive/%f </dev/null'
archive_timeout = 86400
max_wal_senders = 32
max_wal_size = 32GB 
min_wal_size = 8GB
checkpoint_timeout = 30min
checkpoint_completion_target = 0.8
wal_keep_segments = 20000
hot_standby = on
max_replication_slots = 32
hot_standby_feedback = on
vacuum_defer_cleanup_age = 0 
random_page_cost = 1.3 
effective_cache_size = 32GB
wal_sync_method = open_datasync
wal_buffers = 8MB
wal_writer_delay = 10ms
work_mem = 8MB
maintenance_work_mem = 128MB
wal_log_hints = on
full_page_writes = on

#pg_stat_statements
pg_stat_statements.max = 10000   
pg_stat_statements.track = all
pg_stat_statements.track_utility=off

#log set
log_destination = 'stderr'
logging_collector = on
log_truncate_on_rotation = on
log_directory = '/service/logs/software/pgsql/pg_log'		
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'	
log_file_mode = 0600		
log_rotation_age = 1d			
log_rotation_size = 100MB	
log_min_duration_statement = 200
#log_line_prefix = '%t [%p-%l] %q%u@%d'
log_timezone = 'PRC'
log_checkpoints = on
log_connections = on
log_disconnections = on
log_error_verbosity = verbose
log_lock_waits = on
log_statement = 'ddl'
log_line_prefix = '%m %p %u %d %r'

#autovacuum set 
autovacuum = on
log_autovacuum_min_duration = 0
autovacuum_max_workers = 10               
autovacuum_naptime = 30s                   
autovacuum_vacuum_scale_factor = 0.1    
autovacuum_analyze_scale_factor = 0.2  
autovacuum_freeze_max_age = 1600000000
autovacuum_multixact_freeze_max_age = 1600000000
vacuum_freeze_table_age = 1500000000
vacuum_multixact_freeze_table_age = 1500000000
auth_delay.milliseconds = 5000           
auto_explain.log_min_duration = 5000     
auto_explain.log_analyze = true
auto_explain.log_verbose = true
auto_explain.log_buffers = true
auto_explain.log_nested_statements = true

#other set
stats_temp_directory = '/service/databases/postgresql/run/9.5-main.pg_stat_tmp'
datestyle = 'iso, mdy'
timezone = 'PRC'
lc_messages = 'en_US.UTF-8'		
lc_monetary = 'en_US.UTF-8'			
lc_numeric = 'en_US.UTF-8'		
lc_time = 'en_US.UTF-8'		
default_text_search_config = 'pg_catalog.english'
deadlock_timeout = 1s
max_locks_per_transaction = 100
shared_preload_libraries = 'pg_pathman,pg_stat_statements'
#max_standby_streaming_delay = 300s

**Comment by MoonInsung** [comment]
Dear @ZSH9053 

The error message says that it is currently in the status of recovery.
Therefore, please try to back up after the recovery is completed.

And I apologize for this comment. 
This issue was registered about a year ago, 
so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
