### ISSUE TITLE
pgut.c--compile error

### ISSUE THREAD

**Issue by yang-rong-0814** [ossc-db/pg_rman#147]
Compile error was accured because of related changes in PG 10
Error message:
libpq/pqsignal.h:40:41: error: unknown type name ‘pqsigfunc’
 extern pqsigfunc pqsignal_pm(int signo, pqsigfunc func);

related commit:
https://github.com/postgres/postgres/commit/4e95733b08648dbe6c39600521608bdf0cc80f44#diff-f2c85e0d0267a1c3481ffc7159cbb4b52486a402fa51e99c8b35889a9746bfd2

This commit contains ‘pqsigfunc’ which defined in src/include/port.h

This error can be fix by applying commit:
https://github.com/ossc-db/pg_rman/commit/e81e3c3e74e049a03a52b9c29684be836dae2fa8

Maybe we have forgotten to apply this on branch REL_10_STABLE?

The same problem was accured on  REL_11_STABLE too.

**Comment by MoonInsung** [comment]
Sorry for the late reply.
Thank you for finding the bug.

We solved the problem with the commit below.
  https://github.com/ossc-db/pg_rman/commit/365707c710cd4f204954db8c2fa945ef67d81424
And we released version 1.3.11 that fixed this issue.

Best regards.
Moon.
