### ISSUE TITLE
pg 11.8 centos 7.4 make error

### ISSUE THREAD

**Issue by longtian001** [ossc-db/pg_rman#148]
OS info:
--# more /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
[root@pg11 pg_rman-1.3.9]#

PG info:
install from source:
--# /opt/pgsql/11.8/bin/psql -V
psql (PostgreSQL) 11.8
--#

pg_rman version: 1.3.9

error info :
--# export PATH=/opt/pgsql/11.8/bin:$PATH
--# export LD_LBRARY_PATH=/opt/pgsql/11.8/lib:$LD_LBRARY_PATH
--# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -I/opt/pgsql/11.8/include -lm -I. -I./ -I/opt/pgsql/11.8/include/server -I/opt/pgsql/11.8/include/internal  -D_GNU_SOURCE   -c -o backup.o backup.c
backup.c: In function ‘do_backup’:
backup.c:887:2: warning: passing argument 2 of ‘get_controlfile’ from incompatible pointer type [enabled by default]
  controlFile = get_controlfile(pgdata, &crc_ok);
  ^
In file included from backup.c:22:0:
/opt/pgsql/11.8/include/server/common/controldata_utils.h:15:25: note: expected ‘const char *’ but argument is of type ‘_Bool *’
 extern ControlFileData *get_controlfile(const char *DataDir, const char *progname, bool *crc_ok_p);
                         ^
backup.c:887:2: error: too few arguments to function ‘get_controlfile’
  controlFile = get_controlfile(pgdata, &crc_ok);
  ^
In file included from backup.c:22:0:
/opt/pgsql/11.8/include/server/common/controldata_utils.h:15:25: note: declared here
 extern ControlFileData *get_controlfile(const char *DataDir, const char *progname, bool *crc_ok_p);
                         ^
backup.c: In function ‘init_data_checksum_enabled’:
backup.c:2141:3: warning: passing argument 2 of ‘get_controlfile’ from incompatible pointer type [enabled by default]
   controlFile = get_controlfile(pgdata, &crc_ok);
   ^
In file included from backup.c:22:0:
/opt/pgsql/11.8/include/server/common/controldata_utils.h:15:25: note: expected ‘const char *’ but argument is of type ‘_Bool *’
 extern ControlFileData *get_controlfile(const char *DataDir, const char *progname, bool *crc_ok_p);
                         ^
backup.c:2141:3: error: too few arguments to function ‘get_controlfile’
   controlFile = get_controlfile(pgdata, &crc_ok);
   ^
In file included from backup.c:22:0:
/opt/pgsql/11.8/include/server/common/controldata_utils.h:15:25: note: declared here
 extern ControlFileData *get_controlfile(const char *DataDir, const char *progname, bool *crc_ok_p);
                         ^
make: *** [backup.o] Error 1
[root@pg11 pg_rman-1.3.9]#

**Comment by MoonInsung** [comment]
Sorry for the late reply.
For the pg_rman, each version of the PostgreSQL has a separate branch.
Did you use the branch used by PostgreSQL 11 version(REL_11_STABLE)?
The error appears to be the source code used by REL_12_STABLE, REL_12_STABLE, REL_13_STABLE and master Branch.
Please use the REL_11_STABLE branch.
 https://github.com/ossc-db/pg_rman/tree/REL_11_STABLE

Best regards.
Moon.

**Comment by abdoali786** [comment]
Facing similar issue with postgres 12 on RMAN 12 version.... Can someone pls check and advise... Thanks in advance !!

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
sh-4.4$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.2 (Ootpa)
sh-4.4$  env | grep LIB
LD_LIBRARY_PATH=/postgres/PGSQL_12.1//lib
sh-4.4$ env | grep HOME
PGHOME=/postgres/PGSQL_12.1/
HOME=/home/postgres
sh-4.4$ psql
psql (12.1)
Type "help" for help.

postgres=# exit
sh-4.4$ tmake install
sh: tmake: command not found
sh-4.4$ make install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -I/postgres/PGSQL_12.1/include -lm -I. -I./ -I/postgres/PGSQL_12.1/include/server -I/postgres/PGSQL_12.1/include/internal  -D_GNU_SOURCE   -c -o data.o data.c
data.c: In function ‘backup_data_file’:
data.c:346:11: warning: implicit declaration of function ‘figure_out_segno’ [-Wimplicit-function-declaration]
   segno = figure_out_segno(file->path);
           ^~~~~~~~~~~~~~~~
data.c: At top level:
data.c:1260:1: error: conflicting types for ‘figure_out_segno’
 figure_out_segno(char *filepath)
 ^~~~~~~~~~~~~~~~
data.c:346:11: note: previous implicit declaration of ‘figure_out_segno’ was here
   segno = figure_out_segno(file->path);
           ^~~~~~~~~~~~~~~~
data.c: In function ‘figure_out_segno’:
data.c:1267:8: warning: variable ‘scanned’ set but not used [-Wunused-but-set-variable]
   int  scanned;
        ^~~~~~~
At top level:
data.c:1260:1: warning: ‘figure_out_segno’ defined but not used [-Wunused-function]
 figure_out_segno(char *filepath)
 ^~~~~~~~~~~~~~~~
make: *** [<builtin>: data.o] Error 1
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by mikecaat** [comment]
Hi, 

Thanks for reporting. 

The [build](https://github.com/ossc-db/pg_rman/actions/runs/791886630) status is green, so we can build in ubuntu.


Although I don't have any idea to solve your problem now, 
could you share the following result?

```
$ which pg_config
$ cd pg_rman 
$ git log --oneline | head
```

**Comment by MoonInsung** [comment]
Dear @longtian001 

Is there still a build error?

And I apologize for this comment. 
If you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
