### ISSUE TITLE
arc_srv_log_management test fails on master.

### ISSUE THREAD

**Issue by bwtakacy** [ossc-db/pg_rman#15]
This seems to be caused by commit https://github.com/postgres/postgres/commit/3971f64843b02e4a55d854156bd53e46a0588e45.

**Comment by bwtakacy** [comment]
This commit change to log some additional messages on checkpoint and update the timestamp of log files.

From the commit messages, this changes is a temporal one but it is better to fix the regression tests.

**Comment by bwtakacy** [comment]
I did commit 480ef4b896fa60fad9025807316a7950d1a6e9a4 for work around.
If the commit on PostgreSQL side is reverted, this also becomes unnecessary.

**Comment by amitlan** [comment]
Maybe time to revert it. Because [Revert "Temporarily make pg_ctl and server shutdown a whole lot chattier."](http://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=c5e9b771275b93b09eec6b760677fe6c5e726ab2)

**Comment by bwtakacy** [comment]
Thanks for notifying!

I will revert it.

**Comment by bwtakacy** [comment]
Done.

Thanks!

**Comment by amitlan** [comment]
Thanks!
