### ISSUE TITLE
pg_rman --compress-data

### ISSUE THREAD

**Issue by cmodomingo** [ossc-db/pg_rman#17]
Hi,

I tried to execute this nohup pg_rman backup --dbname=postgres --pgdata=/pgsql/g01/db01/pgrex101/pgdata/ --compress-data --verbose --progress --backup-mode=full

However, it seems that it does not compress that backup.

pg_rman show

 StartTime           Mode  Duration    Size   TLI  Status
2016-04-04 15:28:40  FULL       28m   327GB     6  DONE

Is there anyting wrong I'm doing?

Thank you in advance.

**Comment by bwtakacy** [comment]
Hi,

The `pg_rman show` does not display whether each backup is compressed or not.
Please run `pg_rman show detail` and check the 'Compressed' column.

By the way, how much is the target database size?
In order to confirm whether the backup is truly compressed, you need to compare the database size and the backup size.

**Comment by cmodomingo** [comment]
Hi thank you for the quick response. Anyway,i'm now able to have the compression worked.

Here's what happened, I compiled postgresql without-zlib then installed pg_rman. I tried to use pg_rman with compression and it does not permit since postgresql is compiled without zlib. I then recompiled it with zlib but didn't reinstalled pg_rman thus I reported that it is not compressing. After trying to reinstall pg_rman, compression for the backup works.

Again thank you!

**Comment by bwtakacy** [comment]
Thanks for reporting!
I'm happy to hear you suceed :smile: 

I feel we should mention about this condition in documentation or else.

**Comment by bwtakacy** [comment]
Hmm, I found that pg_rman show warning in such a case.

```
WARNING: compression is not available in this installation
```

But, this is not meaningful.
I will modify it like

```
WARNING: compression was required but cannot be used in this environment
HINT: Please check the PostgreSQL is built with zlib.
```

**Comment by cmodomingo** [comment]
Hi,

Yes I'm able to get that error message that's why I recompiled PostgreSQL but after I recompiled I didn't reinstall pg_rman thus compression didn't work but after reinstalling pg_rman compression worked :)

**Comment by bwtakacy** [comment]
Right, not only PostgreSQL but also pg_rman need to be re-install.
This should be informed by error message.

**Comment by amitlan** [comment]
Thanks @cmodomingo for report and @bwtakacy for followup.

I am not sure how much work it would be, but does it seem desirable to link with zlib ourselves, that is, irrespective of whether PostgreSQL in a given environment is built with zlib or not?  Although, that has a disadvantage that zlib-devel would now become a dependency of pg_rman itself and also we'd need to figure out a recipe to determine whether we have zlib in a given build environment.

Am I missing something? Are there any other such dependencies?

**Comment by bwtakacy** [comment]
That's sounds good idea.

PostgreSQL uses zlib for compression in pg_dump and pg_restore.
Pg_rman uses lib for compression in own backup. So, they are not related, theoretically.

In current implementation, pg_rman derived the zlib dependency from PostgreSQL by LIBS in Makefile.
We can set independently from PostgreSQL side.

**Comment by amitlan** [comment]
Also HAVE_LIBZ, which pg_rman inherits from pg_config.h indirectly via postgres_fe.h. PostgreSQL, if configured with zlib (or rather without --without-zlib), sets HAVE_ZLIB in pg_config.h.

Maybe, we would need pg_rman_config.h of our own?  Any thoughts on doing it in a simpler manner?

**Comment by bwtakacy** [comment]
How about this?
* change to use HAVE_LIBZ to custom flag RMAN_HAVE_LIBZ,
* define RMAN_HAVE_LIBZ in pg_rman.h

**Comment by amitlan** [comment]
Yeah, that's an idea.  What I was thinking is to have something like:

```
#ifndef HAVE_LIBZ
#define HAVE_LIBZ 1
```

So, that if Postgres's configure didn't set it already, pg_rman will have set it by its own check.  Below is the portion from Postgres's configure below where that check occurs:

```
if test "$with_zlib" = yes; then
  { $as_echo "$as_me:${as_lineno-$LINENO}: checking for inflate in -lz" >&5
$as_echo_n "checking for inflate in -lz... " >&6; }
if ${ac_cv_lib_z_inflate+:} false; then :
  $as_echo_n "(cached) " >&6
else
  ac_check_lib_save_LIBS=$LIBS
LIBS="-lz  $LIBS"
cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/* end confdefs.h.  */

/* Override any GCC internal prototype to avoid an error.
   Use char because int might match the return type of a GCC
   builtin and then its argument prototype would still apply.  */
#ifdef __cplusplus
extern "C"
#endif
char inflate ();
int
main ()
{
return inflate ();
  ;
  return 0;
}
_ACEOF
if ac_fn_c_try_link "$LINENO"; then :
  ac_cv_lib_z_inflate=yes
else
  ac_cv_lib_z_inflate=no
fi
rm -f core conftest.err conftest.$ac_objext \
    conftest$ac_exeext conftest.$ac_ext
LIBS=$ac_check_lib_save_LIBS
fi
{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_z_inflate" >&5
$as_echo "$ac_cv_lib_z_inflate" >&6; }
if test "x$ac_cv_lib_z_inflate" = xyes; then :
  cat >>confdefs.h <<_ACEOF
#define HAVE_LIBZ 1
_ACEOF

  LIBS="-lz $LIBS"
else
  as_fn_error $? "zlib library not found
If you have zlib already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-zlib to disable zlib support." "$LINENO" 5
fi

fi
```

We would have figure out how to incorporate that into pg_rman's Makefile. Or maybe we will need to have our own configure.in and edit our installation instructions to add one more step. That's beginning to sound like some work.

**Comment by bwtakacy** [comment]
Ah, your idea using ifndef~define is more simple.

If can, I want to choose the way without configure.in because it seems to be a little troublesome to maintain the own configure.in, considering many platform like Ubuntu, Mac OS, etc..

**Comment by amitlan** [comment]
Yeah, that's the kind of trouble I too want to remain far from as much as possible.

By the way, in my last message, I posted a portion from configure file (which I just learned is actually the output after running `autoconf` on `configure.in`). We can achieve that using something as short as the following:

```
$ cat configure.ac
AC_INIT(myconfig, version-0.1)
AC_PROG_CC
AC_CHECK_HEADERS(zlib.h)
AC_CHECK_LIB(z, deflate)
$ autoconf /tmp/configure.ac > configure
$ ./configure
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for deflate in -lz... yes
[amit tmp]$ vim configure.ac
```

So if we want to consider going this way, we should ship both configure.ac and configure in the source repository like Postgres does.  Do you think that's still asking for maintenance burden?  Maybe, I am missing something.

**Comment by ooyamams** [comment]
Hi! I have fixed the message. If it is OK, please marge it.

**Comment by bwtakacy** [comment]
@ooyamams Thanks for RP. I will check it. This should be a quick fix for a while.

@amitlan It seems that the autoconf makes things very simple and there become no maintenance trouble:) I think we try to create a patch for using own configure file.

Thought?

**Comment by amitlan** [comment]
Agreed. I am still looking for a way to incorporate autoconf-based configure script.

**Comment by amitlan** [comment]
I tried to add pg_rman's own configure script in PR #19.

When playing with it I started wondering whether anyone builds pg_rman where its choice of building with or without zlib is different from Postgres installed in the same environment.  Maybe there is some value in this ability.  For whatever reason, Postgres may have been build `--without-zlib` but we want pg_rman to be built with it.  But then again, main reason to build `--without-zlib` is that environment does not have zlib (and/or headers) at all, so one cannot build pg_rman with different option. Hmm...

**Comment by bwtakacy** [comment]
Thanks, @amitlan !
That's a great advance.

>When playing with it I started wondering whether anyone builds pg_rman where the choice of building with or without zlib is different from Postgres installed (maybe also built) in the same environment. But maybe there is some value in this ability. For whatever reason, Postgres may have been built --without-zlib (even if zlib exists), but we want pg_rman to be built with it. Seems unlikely but...

Hmm,
I feel we should re-consider what to do for this.
As you pointed out, the custom configure script makes someting better but something worse or annoying. We need to decide which side is more important.

I summerised pros and cons.
How do you think, @amitlan , @ooyamams ?

## custom configure script
  * good: 
   + does not  depend on PostgreSQL side
   + enable to add own dependency easily
  * not so good:
   + PostgreSQL is built with zlib as default, so this feature is not required.
   + change the build step; maybe this is not a problem because configure && make $$ make install is usual step.

**Comment by amitlan** [comment]
Thanks.  Actually, I came to realize that we should not have own configure script after all.  In short, I withdraw my proposal and hence the PR.

That realization came from a point of view that pg_rman is really part of Postgres's ecosystem.  We explicitly need `PATH` to include `pg_config`, which says enough.  Any tool that uses Postgres's libraries/API should really use the build config that it provides via `pg_config`. In that regard, we should treat pg_rman as pg_dump/restore/basebackup, etc., which by the way do not have their own configure scripts.

Thoughts?

**Comment by bwtakacy** [comment]
That's sounds reasonable. 
So, let's decide to choose current way.

>EDIT: Sorry to have unduly taken your time.

Never mind:)
I take time because I want to.

**Comment by amitlan** [comment]
Closing this now.  Hope @cmodomingo finds the new warning message (and hint) helpful in future encounters. :)

**Comment by bwtakacy** [comment]
Thank you, @amitlan  for all your effort at this issue !

**Comment by cmodomingo** [comment]
Thank you everyone for taking all the time and effort on this :) really appreciate it..
