### ISSUE TITLE
issue when install pg_rman-1.3.11-pg13

### ISSUE THREAD

**Issue by tery-sun** [ossc-db/pg_rman#178]
$ tar zxvf pg_rman-1.3.11-pg13.tar.gz 
$ cd pg_rman-1.3.11-pg13
$ make && make install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -I/usr/include/postgresql -lm -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o backup.o backup.c
In file included from backup.c:10:
pg_rman.h:13:10: fatal error: postgres_fe.h: No such file or directory
   13 | #include "postgres_fe.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: backup.o] Error 1

**Comment by tery-sun** [comment]
I am using Ubuntu 20.04

**Comment by mikecaat** [comment]
Hi, @tery-sun,

Thanks for your reporting.

The error seems that it can't detect postgresql libraries.
Please check if the postgresql is already installed and the results of the following command.

```
$ which pg_config
```

Regards,

**Comment by mikecaat** [comment]
You can see what a package need to be installed.

```
$ apt-file search postgres_fe
libpq-dev: /usr/include/postgresql/internal/postgres_fe.h
postgresql-server-dev-10: /usr/include/postgresql/10/server/postgres_fe.h
postgresql-server-dev-11: /usr/include/postgresql/11/server/postgres_fe.h
postgresql-server-dev-12: /usr/include/postgresql/12/server/postgres_fe.h
postgresql-server-dev-13: /usr/include/postgresql/13/server/postgres_fe.h
postgresql-server-dev-8.2: /usr/include/postgresql/8.2/server/postgres_fe.h
postgresql-server-dev-8.3: /usr/include/postgresql/8.3/server/postgres_fe.h
postgresql-server-dev-8.4: /usr/include/postgresql/8.4/server/postgres_fe.h
postgresql-server-dev-9.0: /usr/include/postgresql/9.0/server/postgres_fe.h
postgresql-server-dev-9.1: /usr/include/postgresql/9.1/server/postgres_fe.h
postgresql-server-dev-9.2: /usr/include/postgresql/9.2/server/postgres_fe.h
postgresql-server-dev-9.3: /usr/include/postgresql/9.3/server/postgres_fe.h
postgresql-server-dev-9.4: /usr/include/postgresql/9.4/server/postgres_fe.h
postgresql-server-dev-9.5: /usr/include/postgresql/9.5/server/postgres_fe.h
postgresql-server-dev-9.6: /usr/include/postgresql/9.6/server/postgres_fe.h
```

**Comment by tery-sun** [comment]
thanks mike, resolved!
apt-file search postgres_fe
apt install -y postgresql-server-dev-13
