### ISSUE TITLE
--recovery-target-action unsupported

### ISSUE THREAD

**Issue by hard88** [ossc-db/pg_rman#182]

**Comment by MoonInsung** [comment]
Dear @hard88 

Thank you for your opinion!!

Yes. Currently, pg_rman does not support options for "--recovery-target-action".
However, if any users need to check if the expected data has been recovered, 
it should manually add the "--recovery-target-action".

If the pg_rman adds these options, it will be a very convenient function.
And, I think that the pg_rman can easily add new functions.

Best regards.
Moon.

**Comment by hard88** [comment]
Thank you.
