### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by lgsantosrj** [ossc-db/pg_rman#20]
I have downloaded pg_rman-1.3.2-pg95.tar.gz for a CentOs 6.7 over PostgreSql 9.5 and the Make command returned the error bellow. Please, need help to find out what am I doing wrong. Thanks in advance.

[root@localhost pg_rman-1.3.2]# make
make: pg_config: Command not found
cc    -c -o backup.o backup.c
In file included from backup.c:10:
pg_rman.h:12:25: error: postgres_fe.h: No such file or directory
pg_rman.h:15:22: error: libpq-fe.h: No such file or directory
pg_rman.h:17:34: error: access/xlog_internal.h: No such file or directory
In file included from pg_rman.h:18,
                 from backup.c:10:
pgut/pgut.h:14:25: error: pqexpbuffer.h: No such file or directory
In file included from pg_rman.h:18,
                 from backup.c:10:
pgut/pgut.h:100: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
pgut/pgut.h:112: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
pgut/pgut.h:113: error: expected ‘)’ before ‘*’ token
pgut/pgut.h:114: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
pgut/pgut.h:115: error: expected ‘)’ before ‘*’ token

**Comment by bwtakacy** [comment]
It seems to be caused because the PostgreSQL devel package is not installed in your environment.
Try to install postgresql95-devel rpm.
