### ISSUE TITLE
pg_rman 1.3.2 over postgresql 9.5 running CentOS 6

### ISSUE THREAD

**Issue by lgsantosrj** [ossc-db/pg_rman#21]
I did not find in the link https://github.com/ossc-db/pg_rman/releases (download link) a rpm package for CentOs 6. Just pg_rman-1.3.2-1.pg95.rhel7.x86_64.rpm for CentOs 7. Is that possible to publish a rpm pachage for postgres 9.5 and CentOs 6? Thanks in advance.

**Comment by ooyamams** [comment]
Hi! @lgsantosrj
OK, we will create a rpm for CentOS 6. Please wait ;)

**Comment by lgsantosrj** [comment]
I really appreciate it! Thanks you all!

**Comment by ooyamams** [comment]
@lgsantosrj I attached it. Please use!
https://github.com/ossc-db/pg_rman/releases

**Comment by lgsantosrj** [comment]
You are great!
Best regards!
