### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by jordan-huangwei** [ossc-db/pg_rman#22]
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -I/usr/include/postgresql -lm -I. -I./ -I/usr/include/postgresql/9.4/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o backup.o backup.c
In file included from pgut/pgut.h:14:0,
                 from pg_rman.h:18,
                 from backup.c:10:
/usr/include/postgresql/internal/pqexpbuffer.h:149:13: warning: no previous prototype for ‘printfPQExpBuffer’ [-Wmissing-prototypes]
 extern void printfPQExpBuffer(PQExpBuffer str, const char *fmt,...) pg_attribute_printf(2, 3);
             ^
/usr/include/postgresql/internal/pqexpbuffer.h: In function ‘printfPQExpBuffer’:
/usr/include/postgresql/internal/pqexpbuffer.h:149:69: error: expected declaration specifiers before ‘pg_attribute_printf’
 extern void printfPQExpBuffer(PQExpBuffer str, const char *fmt,...) pg_attribute_printf(2, 3);
                                                                     ^
/usr/include/postgresql/internal/pqexpbuffer.h:158:69: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘pg_attribute_printf’
 extern void appendPQExpBuffer(PQExpBuffer str, const char *fmt,...) pg_attribute_printf(2, 3);
                                                                     ^
/usr/include/postgresql/internal/pqexpbuffer.h:165:13: error: storage class specified for parameter ‘appendPQExpBufferStr’
 extern void appendPQExpBufferStr(PQExpBuffer str, const char *data);
             ^
/usr/include/postgresql/internal/pqexpbuffer.h:172:13: error: storage class specified for parameter ‘appendPQExpBufferChar’
 extern void appendPQExpBufferChar(PQExpBuffer str, char ch);
             ^
/usr/include/postgresql/internal/pqexpbuffer.h:179:13: error: storage class specified for parameter ‘appendBinaryPQExpBuffer’
 extern void appendBinaryPQExpBuffer(PQExpBuffer str,
             ^
In file included from pgut/pgut.h:16:0,
                 from pg_rman.h:18,
                 from backup.c:10:
/usr/include/assert.h:69:13: error: storage class specified for parameter ‘__assert_fail’
 extern void __assert_fail (const char *__assertion, const char *__file,
             ^
/usr/include/assert.h:74:13: error: storage class specified for parameter ‘__assert_perror_fail’
 extern void __assert_perror_fail (int __errnum, const char *__file,
             ^
/usr/include/assert.h:81:13: error: storage class specified for parameter ‘__assert’
 extern void __assert (const char *__assertion, const char *__file, int __line)
             ^
In file included from pgut/pgut.h:17:0,
                 from pg_rman.h:18,
                 from backup.c:10:
/usr/include/x86_64-linux-gnu/sys/time.h:61:37: error: storage class specified for parameter ‘__timezone_ptr_t’
 typedef struct timezone *__restrict __timezone_ptr_t;
                                     ^
/usr/include/x86_64-linux-gnu/sys/time.h:72:5: error: expected declaration specifiers or ‘...’ before ‘__timezone_ptr_t’
     __timezone_ptr_t __tz) __THROW __nonnull ((1));
     ^
/usr/include/x86_64-linux-gnu/sys/time.h:77:12: error: storage class specified for parameter ‘settimeofday’
 extern int settimeofday (const struct timeval *__tv,
            ^
/usr/include/x86_64-linux-gnu/sys/time.h:85:12: error: storage class specified for parameter ‘adjtime’
 extern int adjtime (const struct timeval *__delta,
            ^
/usr/include/x86_64-linux-gnu/sys/time.h:118:29: error: storage class specified for parameter ‘__itimer_which_t’
 typedef enum __itimer_which __itimer_which_t;
                             ^
/usr/include/x86_64-linux-gnu/sys/time.h:125:23: error: expected declaration specifiers or ‘...’ before ‘__itimer_which_t’
 extern int getitimer (__itimer_which_t __which,
                       ^
/usr/include/x86_64-linux-gnu/sys/time.h:131:23: error: expected declaration specifiers or ‘...’ before ‘__itimer_which_t’
 extern int setitimer (__itimer_which_t __which,
                       ^
/usr/include/x86_64-linux-gnu/sys/time.h:138:12: error: storage class specified for parameter ‘utimes’
 extern int utimes (const char *__file, const struct timeval __tvp[2])
            ^
/usr/include/x86_64-linux-gnu/sys/time.h:143:12: error: storage class specified for parameter ‘lutimes’
 extern int lutimes (const char *__file, const struct timeval __tvp[2])
            ^
/usr/include/x86_64-linux-gnu/sys/time.h:147:12: error: storage class specified for parameter ‘futimes’
 extern int futimes (int __fd, const struct timeval __tvp[2]) __THROW;
            ^
/usr/include/x86_64-linux-gnu/sys/time.h:154:12: error: storage class specified for parameter ‘futimesat’
 extern int futimesat (int __fd, const char *__file,
            ^
In file included from pg_rman.h:18:0,
                 from backup.c:10:
pgut/pgut.h:38:3: error: storage class specified for parameter ‘YesNo’
 } YesNo;
   ^
pgut/pgut.h:47:3: error: storage class specified for parameter ‘pgut_optsrc’
 } pgut_optsrc;
   ^
pgut/pgut.h:69:2: error: expected specifier-qualifier-list before ‘pgut_optsrc’
  pgut_optsrc allowed; /* allowed source */
  ^
pgut/pgut.h:71:3: error: storage class specified for parameter ‘pgut_option’
 } pgut_option;
   ^
pgut/pgut.h:73:29: error: expected declaration specifiers or ‘...’ before ‘pgut_option’
 typedef void (*pgut_optfn) (pgut_option *opt, const char *arg);
                             ^
pgut/pgut.h:74:16: error: storage class specified for parameter ‘pgut_atexit_callback’
 typedef void (*pgut_atexit_callback)(bool fatal, void *userdata);
                ^
pgut/pgut.h:79:21: error: storage class specified for parameter ‘PROGRAM_NAME’
 extern const char  *PROGRAM_NAME;
                     ^
pgut/pgut.h:80:21: error: storage class specified for parameter ‘PROGRAM_VERSION’
 extern const char  *PROGRAM_VERSION;
                     ^
pgut/pgut.h:81:21: error: storage class specified for parameter ‘PROGRAM_URL’
 extern const char  *PROGRAM_URL;
                     ^
pgut/pgut.h:82:21: error: storage class specified for parameter ‘PROGRAM_ISSUES’
 extern const char  *PROGRAM_ISSUES;
                     ^
pgut/pgut.h:84:13: error: storage class specified for parameter ‘pgut_help’
 extern void pgut_help(bool details);
             ^
pgut/pgut.h:89:21: error: storage class specified for parameter ‘dbname’
 extern const char  *dbname;
                     ^
pgut/pgut.h:90:21: error: storage class specified for parameter ‘host’
 extern const char  *host;
                     ^
pgut/pgut.h:91:21: error: storage class specified for parameter ‘port’
 extern const char  *port;
                     ^
pgut/pgut.h:92:21: error: storage class specified for parameter ‘username’
 extern const char  *username;
                     ^
pgut/pgut.h:93:18: error: storage class specified for parameter ‘password’
 extern char     *password;
                  ^
pgut/pgut.h:94:15: error: storage class specified for parameter ‘quiet’
 extern bool   quiet;
               ^
pgut/pgut.h:97:14: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘prompt_password’
 extern YesNo prompt_password;
              ^
pgut/pgut.h:100:19: error: storage class specified for parameter ‘connection’
 extern PGconn    *connection;
                   ^
pgut/pgut.h:101:15: error: storage class specified for parameter ‘interrupted’
 extern bool   interrupted;
               ^
pgut/pgut.h:103:13: error: storage class specified for parameter ‘help’
 extern void help(bool details);
             ^
pgut/pgut.h:104:47: error: expected declaration specifiers or ‘...’ before ‘pgut_option’
 extern int pgut_getopt(int argc, char **argv, pgut_option options[]);
                                               ^
pgut/pgut.h:105:44: error: expected declaration specifiers or ‘...’ before ‘pgut_option’
 extern void pgut_readopt(const char *path, pgut_option options[], int elevel);
                                            ^
pgut/pgut.h:106:30: error: expected declaration specifiers or ‘...’ before ‘pgut_atexit_callback’
 extern void pgut_atexit_push(pgut_atexit_callback callback, void *userdata);
                              ^
pgut/pgut.h:107:29: error: expected declaration specifiers or ‘...’ before ‘pgut_atexit_callback’
 extern void pgut_atexit_pop(pgut_atexit_callback callback, void *userdata);
                             ^
pgut/pgut.h:112:16: error: storage class specified for parameter ‘pgut_connect’
 extern PGconn *pgut_connect(void);
                ^
pgut/pgut.h:113:13: error: storage class specified for parameter ‘pgut_disconnect’
 extern void pgut_disconnect(PGconn *conn);
             ^
pgut/pgut.h:114:18: error: storage class specified for parameter ‘pgut_execute’
 extern PGresult *pgut_execute(PGconn* conn, const char *query, int nParams, const char **params);
                  ^
pgut/pgut.h:115:13: error: storage class specified for parameter ‘pgut_command’
 extern void pgut_command(PGconn* conn, const char *query, int nParams, const char **params);
             ^
pgut/pgut.h:116:13: error: storage class specified for parameter ‘pgut_send’
 extern bool pgut_send(PGconn* conn, const char *query, int nParams, const char **params);
             ^
pgut/pgut.h:117:12: error: storage class specified for parameter ‘pgut_wait’
 extern int pgut_wait(int num, PGconn *connections[], struct timeval *timeout);
            ^
pgut/pgut.h:119:16: error: storage class specified for parameter ‘reconnect’
 extern PGconn *reconnect(void);
                ^
pgut/pgut.h:120:13: error: storage class specified for parameter ‘disconnect’
 extern void disconnect(void);
             ^
pgut/pgut.h:122:20: error: storage class specified for parameter ‘pgut_get_host’
 extern const char *pgut_get_host(void);
                    ^
pgut/pgut.h:123:20: error: storage class specified for parameter ‘pgut_get_port’
 extern const char *pgut_get_port(void);
                    ^
pgut/pgut.h:124:13: error: storage class specified for parameter ‘pgut_set_host’
 extern void pgut_set_host(const char *new_host);
             ^
pgut/pgut.h:125:13: error: storage class specified for parameter ‘pgut_set_port’
 extern void pgut_set_port(const char *new_port);
             ^
pgut/pgut.h:127:18: error: storage class specified for parameter ‘execute’
 extern PGresult *execute(const char *query, int nParams, const char **params);
                  ^
pgut/pgut.h:128:13: error: storage class specified for parameter ‘command’
 extern void command(const char *query, int nParams, const char **params);
             ^
pgut/pgut.h:133:14: error: storage class specified for parameter ‘pgut_malloc’
 extern void *pgut_malloc(size_t size);
              ^
pgut/pgut.h:134:14: error: storage class specified for parameter ‘pgut_realloc’
 extern void *pgut_realloc(void *p, size_t size);
              ^
pgut/pgut.h:135:14: error: storage class specified for parameter ‘pgut_strdup’
 extern char *pgut_strdup(const char *str);
              ^
pgut/pgut.h:136:14: error: storage class specified for parameter ‘strdup_with_len’
 extern char *strdup_with_len(const char *str, size_t len);
              ^
pgut/pgut.h:137:14: error: storage class specified for parameter ‘strdup_trim’
 extern char *strdup_trim(const char *str);
              ^
pgut/pgut.h:145:14: error: storage class specified for parameter ‘pgut_fopen’
 extern FILE *pgut_fopen(const char *path, const char *mode, bool missing_ok);
              ^
pgut/pgut.h:172:13: error: storage class specified for parameter ‘elog’
 extern void elog(int elevel, const char *fmt, ...)
             ^
pgut/pgut.h:174:21: error: storage class specified for parameter ‘format_elevel’
 extern const char * format_elevel(int elevel);
                     ^
pgut/pgut.h:175:13: error: storage class specified for parameter ‘pgut_errstart’
 extern bool pgut_errstart(int elevel);
             ^
pgut/pgut.h:176:13: error: storage class specified for parameter ‘pgut_errfinish’
 extern void pgut_errfinish(int dummy, ...);
             ^
pgut/pgut.h:177:13: error: storage class specified for parameter ‘pgut_error’
 extern void pgut_error(int elevel, const char *msg, const char *detail, const char *hint);
             ^
pgut/pgut.h:178:12: error: storage class specified for parameter ‘errcode’
 extern int errcode(int errcode);
            ^
pgut/pgut.h:179:12: error: storage class specified for parameter ‘errmsg’
 extern int errmsg(const char *fmt, ...)
            ^
pgut/pgut.h:181:12: error: storage class specified for parameter ‘errdetail’
 extern int errdetail(const char *fmt, ...)
            ^
pgut/pgut.h:183:12: error: storage class specified for parameter ‘errhint’
 extern int errhint(const char *fmt, ...)
            ^
pgut/pgut.h:222:13: error: storage class specified for parameter ‘appendStringInfoVA_c’
 extern bool appendStringInfoVA_c(StringInfo str, const char *fmt, va_list args)
             ^
pgut/pgut.h:224:12: error: storage class specified for parameter ‘appendStringInfoFile’
 extern int appendStringInfoFile(StringInfo str, FILE *fp);
            ^
pgut/pgut.h:225:12: error: storage class specified for parameter ‘appendStringInfoFd’
 extern int appendStringInfoFd(StringInfo str, int fd);
            ^
pgut/pgut.h:226:13: error: storage class specified for parameter ‘trimStringBuffer’
 extern void trimStringBuffer(StringInfo str);
             ^
pgut/pgut.h:228:13: error: storage class specified for parameter ‘parse_bool’
 extern bool parse_bool(const char *value, bool *result);
             ^
pgut/pgut.h:229:13: error: storage class specified for parameter ‘parse_bool_with_len’
 extern bool parse_bool_with_len(const char *value, size_t len, bool *result);
             ^
pgut/pgut.h:230:13: error: storage class specified for parameter ‘parse_int32’
 extern bool parse_int32(const char *value, int32 *result);
             ^
pgut/pgut.h:231:13: error: storage class specified for parameter ‘parse_uint32’
 extern bool parse_uint32(const char *value, uint32 *result);
             ^
pgut/pgut.h:232:13: error: storage class specified for parameter ‘parse_int64’
 extern bool parse_int64(const char *value, int64 *result);
             ^
pgut/pgut.h:233:13: error: storage class specified for parameter ‘parse_uint64’
 extern bool parse_uint64(const char *value, uint64 *result);
             ^
pgut/pgut.h:234:13: error: storage class specified for parameter ‘parse_time’
 extern bool parse_time(const char *value, time_t *time);
             ^
pgut/pgut.h:247:12: error: storage class specified for parameter ‘wait_for_socket’
 extern int wait_for_socket(int sock, struct timeval *timeout);
            ^
pgut/pgut.h:248:12: error: storage class specified for parameter ‘wait_for_sockets’
 extern int wait_for_sockets(int nfds, fd_set *fds, struct timeval *timeout);
            ^
In file included from /usr/include/postgresql/9.4/server/storage/bufpage.h:19:0,
                 from pg_rman.h:20,
                 from backup.c:10:
/usr/include/postgresql/9.4/server/storage/item.h:17:17: error: storage class specified for parameter ‘Item’
 typedef Pointer Item;
                 ^
In file included from /usr/include/postgresql/9.4/server/storage/off.h:17:0,
                 from /usr/include/postgresql/9.4/server/storage/bufpage.h:20,
                 from pg_rman.h:20,
                 from backup.c:10:
/usr/include/postgresql/9.4/server/storage/itemid.h:29:3: error: storage class specified for parameter ‘ItemIdData’
 } ItemIdData;
   ^
/usr/include/postgresql/9.4/server/storage/itemid.h:31:20: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
 typedef ItemIdData *ItemId;
                    ^
/usr/include/postgresql/9.4/server/storage/itemid.h:46:16: error: storage class specified for parameter ‘ItemOffset’
 typedef uint16 ItemOffset;
                ^
/usr/include/postgresql/9.4/server/storage/itemid.h:47:16: error: storage class specified for parameter ‘ItemLength’
 typedef uint16 ItemLength;
                ^
In file included from /usr/include/postgresql/9.4/server/storage/bufpage.h:20:0,
                 from pg_rman.h:20,
                 from backup.c:10:
/usr/include/postgresql/9.4/server/storage/off.h:24:16: error: storage class specified for parameter ‘OffsetNumber’
 typedef uint16 OffsetNumber;
                ^
In file included from pg_rman.h:20:0,
                 from backup.c:10:
/usr/include/postgresql/9.4/server/storage/bufpage.h:74:17: error: storage class specified for parameter ‘Page’
 typedef Pointer Page;
                 ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:83:16: error: storage class specified for parameter ‘LocationIndex’
 typedef uint16 LocationIndex;
                ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:94:3: error: storage class specified for parameter ‘PageXLogRecPtr’
 } PageXLogRecPtr;
   ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:150:2: error: expected specifier-qualifier-list before ‘PageXLogRecPtr’
  PageXLogRecPtr pd_lsn;  /* LSN: next byte after last byte of xlog
  ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:160:3: error: storage class specified for parameter ‘PageHeaderData’
 } PageHeaderData;
   ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:162:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
 typedef PageHeaderData *PageHeader;
                        ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:392:22: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern void PageInit(Page page, Size pageSize, Size specialSize);
                      ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:393:28: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern bool PageIsVerified(Page page, BlockNumber blkno);
                            ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:394:21: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘PageAddItem’
 extern OffsetNumber PageAddItem(Page page, Item item, Size size,
                     ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:396:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘PageGetTempPage’
 extern Page PageGetTempPage(Page page);
             ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:397:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘PageGetTempPageCopy’
 extern Page PageGetTempPageCopy(Page page);
             ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:398:13: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘PageGetTempPageCopySpecial’
 extern Page PageGetTempPageCopySpecial(Page page);
             ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:399:33: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern void PageRestoreTempPage(Page tempPage, Page oldPage);
                                 ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:399:48: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern void PageRestoreTempPage(Page tempPage, Page oldPage);
                                                ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:400:37: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern void PageRepairFragmentation(Page page);
                                     ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:401:30: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern Size PageGetFreeSpace(Page page);
                              ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:402:35: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern Size PageGetExactFreeSpace(Page page);
                                   ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:403:34: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern Size PageGetHeapFreeSpace(Page page);
                                  ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:404:34: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern void PageIndexTupleDelete(Page page, OffsetNumber offset);
                                  ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:404:45: error: expected declaration specifiers or ‘...’ before ‘OffsetNumber’
 extern void PageIndexTupleDelete(Page page, OffsetNumber offset);
                                             ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:405:34: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern void PageIndexMultiDelete(Page page, OffsetNumber *itemnos, int nitems);
                                  ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:405:45: error: expected declaration specifiers or ‘...’ before ‘OffsetNumber’
 extern void PageIndexMultiDelete(Page page, OffsetNumber *itemnos, int nitems);
                                             ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:406:34: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern char *PageSetChecksumCopy(Page page, BlockNumber blkno);
                                  ^
/usr/include/postgresql/9.4/server/storage/bufpage.h:407:36: error: expected declaration specifiers or ‘...’ before ‘Page’
 extern void PageSetChecksumInplace(Page page, BlockNumber blkno);
                                    ^
In file included from backup.c:10:0:
pg_rman.h:21:28: fatal error: port/pg_crc32c.h: No such file or directory
 #include "port/pg_crc32c.h"
                            ^
compilation terminated.
make: *** [backup.o] Error 1

**Comment by jordan-huangwei** [comment]
ubuntu 14.04

**Comment by amitlan** [comment]
I have never made pg_rman on ubuntu, but found something on web that you can give a try:

```
sudo apt-get install libpq-dev=9.4* libpq5=9.4*
```
