### ISSUE TITLE
The regression tests fail on master

### ISSUE THREAD

**Issue by bwtakacy** [ossc-db/pg_rman#28]
Hi, developers:)

Thanks for trying to implement non-exclusive backup with 9.6.
But, after merging the PR #27, the regression tests become fail.

```
============== running regression test queries        ==============
test init                     ... ok
test option                   ... ok
test show                     ... ok
test delete                   ... FAILED
test purge                    ... ok
test backup                   ... FAILED
test backup_management        ... FAILED
test restore                  ... FAILED
test restore_checksum         ... FAILED
test backup_from_standby      ... FAILED
test arc_srv_log_management   ... FAILED
```

The below is regressin.diff of `delete` test.

```
*** /home/postgres/ossc-db/pg_rman/expected/delete.out  2016-04-27 21:54:35.372018001 +0900
--- /home/postgres/ossc-db/pg_rman/results/delete.out   2016-05-23 22:21:03.683432263 +0900
***************
*** 13,20 ****
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
  try to delete before third backup
! 4
  1
  Number of deleted backups should be 1, is it so?: 1
--- 13,21 ----
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
+ ERROR: not connected
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
  try to delete before third backup
! 3
  1
  Number of deleted backups should be 1, is it so?: 1

======================================================================
```

Some mis-handling of connection?

Thanks.

**Comment by amitlan** [comment]
Thanks for the report Ohnishi-san.  Looking into it.

**Comment by amitlan** [comment]
Quick inspection shows that one issue is related to connection.  Easy to fix so pushed a fix.

Other issue is related to writing `backup_label` file in compressed mode and then decompression fails during restore.  Looking at what is going wrong there.  Perhaps I did not give enough consideration to the compression mode.  A different code path is handling those two files (`backup_label` and `tablespace_map`).

**Comment by amitlan** [comment]
One of the failures requires update to `expected/backup.out`.  The reason is that - on error, we no longer issue a `pg_stop_backup()`, so the following notice has disappeared from that output:

```
- NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
```

Will fix that too.

**Comment by bwtakacy** [comment]
Thanks for investigation, Amit.

We need to fix step by step. Let's starting from easy one. The issue about compression seems to be the last.

**Comment by amitlan** [comment]
Just pushed a combined fix in the form of commit b37c003bc69dc1017003186f3dc8b9fd0df055da
to master.

**Comment by amitlan** [comment]
Seeing that Travis is happy this morning, should we call this closed?

**Comment by amitlan** [comment]
OK, I seem to have figured out why results of the backup test are unreliable.  It turns out to have to with timing after all.  Although some detailed analysis on pg_rman side may be necessary in the long term.  Details follow.

Within `TEST-0010`, sometimes the first command for incremental backup without `--full-backup-on-error` option may fail to be recorded into the backup catalog (after error).  Maybe because the next command (with `--full-backup-on-error`) is run immediately.  If I enter a modest `sleep 0.5` between the two commands, I can get it the test to reliably succeed.  Seems like a band-aid solution though.

**Comment by amitlan** [comment]
And pushed 0e239cd687f1e8a83bd190a43237e4ed337544e9 that temporarily makes the failure of tests to disappear.  However, why sometimes pg_rman fails to write out backup directory (and `backup.ini` therein) is unresolved - remember that is the reason why `pg_rman show` does not show a row corresponding to the failed backup.

**Comment by bwtakacy** [comment]
Sorry for my absence and thanks amit for your effort about this issue.

I' ve confirmed that all the regression tests are passed in my env and Travis.
Though there is an unresolved failure, I think it is okay to close this issue.

Thanks! :smile:
