### ISSUE TITLE
Intermittent failure with test backup

### ISSUE THREAD

**Issue by michaelpq** [ossc-db/pg_rman#35]
Half of the time the backup test fails:
============== running regression test queries        ==============
test init                     ... ok
test backup                   ... FAILED
test backup_from_standby      ... ok
test delete                   ... ok
test option                   ... ok
test purge                    ... ok
test restore                  ... ok
test restore_checksum         ... ok
test show                     ... ok
***************
*** 59,65 ****
  0
  1
  3
! Number of remaining archivelog files: 2
  ###### BACKUP COMMAND TEST-0009 ######
  ###### full backup with keep-srvlog-files and keep-srvlog-days ######
  The number of existing server log files already backuped is greater than 1.
--- 59,65 ----
  0
  1
  3
! Number of remaining archivelog files: 0
  ###### BACKUP COMMAND TEST-0009 ######
  ###### full backup with keep-srvlog-files and keep-srvlog-days ######
  The number of existing server log files already backuped is greater than 1.

======================================================================

I can see that 0e239cd6 has been added as a temporary solution. Could it be possible to at least back-patch that to the other branches?

**Comment by amitlan** [comment]
Thanks for the report.  Didn't see the failure in back-branches at the time the fix was committed, so didn't think of back-patching.  Will do.

**Comment by michaelpq** [comment]
9.4 and 9.5 have been complaining 25%~50% of the time with this test unfortunately. On a Linux VM I was able to reproduce that as well btw, I think that a slower environment makes that easier to happen.
