### ISSUE TITLE
Get rid of the gh-pages branch

### ISSUE THREAD

**Issue by amitlan** [ossc-db/pg_rman#36]
I just came across this news: https://github.com/blog/2228-simpler-github-pages-publishing

So, it seems we can move the content of the gh-pages branch to a `docs/` directory in master branch and remove that branch.

Moreover, I think it will be nicer to create src, include directories as well and reduce the clutter of files in the root directory, but a separate issue for that makes more sense.

**Comment by bwtakacy** [comment]
Fortunately we already have the `doc` directory and can try it easily by renaming it 😃 

Will try?

**Comment by amitlan** [comment]
So, simply pushing that change (directory rename) and changing the settings for GitHub pages will be enough?

**Comment by bwtakacy** [comment]
Thanks!

**Comment by amitlan** [comment]
Done.

Remove the branch as well?

**Comment by bwtakacy** [comment]
Nice. I can access the documentation web pages as before.

> Remove the branch as we

Yeah.

**Comment by amitlan** [comment]
Done too.  It seems to work! :-)

**Comment by bwtakacy** [comment]
👍 

I will do the same changes in other tools.

**Comment by amitlan** [comment]
Thanks a lot!
