### ISSUE TITLE
bug, when set unix_sock='.'

### ISSUE THREAD

**Issue by digoal** [ossc-db/pg_rman#40]
when set unix_socket='.'
in $PGDATA will add a unix socket file. but this file type=?

pg_rman validate
INFO: validate: "2016-08-26 16:19:25" backup, archive log files and server log files by CRC
ERROR: invalid type '?' found in "/data05/digoal/pgbak/20160826/161925/file_database.txt"

vi /data05/digoal/pgbak/20160826/161925/file_database.txt

.s.PGSQL.1921 ? 0 0 0777 2016-08-26 15:35:05

vi dir.c
```
                if (strncmp(path, ".s.PGSQL", 7) != 0 && type != 'f' && type != 'F' && type != 'd' && type != 'l')
                        ereport(ERROR,
                                (errcode(ERROR_CORRUPTED),
                                 errmsg("invalid type '%c' found in \"%s\"", type, file_txt)));
```

**Comment by bwtakacy** [comment]
Thank you for reporting and proposing a quick fix!

In the current implementation pg_rman forgets to handle the Unix domain socket file.
I think it is better to exclude the socket file from a backup because that is ephemeral.

**Comment by amitlan** [comment]
+1

Hopefully, `S_IFSOCK` is the only other file type we will need to handle.

**Comment by bwtakacy** [comment]
Thank you @amitlan for commenting and merging!

**Comment by amitlan** [comment]
Right, I always seem to forget about that. :)

**Comment by bwtakacy** [comment]
Thanks!

**Comment by digoal** [comment]
Thanks.
