### ISSUE TITLE
README.md in non-master branches

### ISSUE THREAD

**Issue by amitlan** [ossc-db/pg_rman#42]
Does it make sense to remove them?

**Comment by bwtakacy** [comment]
Likely so.

Maybe i forgot to remove it when cutting new branches from master.

**Comment by amitlan** [comment]
Today I pushed a README.md change and then sort of hesitated when making the same change in other branches.  I think we should just remove them.  Will do if no issues.

**Comment by bwtakacy** [comment]
+1 for just remove

**Comment by bwtakacy** [comment]
Thanks! :smiley:
