### ISSUE TITLE
Libraries/packages required by pg_rman (build-time dependencies)

### ISSUE THREAD

**Issue by amitlan** [ossc-db/pg_rman#43]
README.md has the following lines:

```
There are some libraries to be installed before.

* pam-devel(libpam-dev)
* readline-devel(libedit-dev)
* zlib-devel
```
Are `pam-devel` or `libpam-dev` and `readline-devel` required to *build* pg_rman?  I think we can remove them from the installation instructions.

I know that `zlib-devel` is required to build pg_rman, so let's keep it in the instructions.

Please point out if I am missing something.

**Comment by bwtakacy** [comment]
Hmm,

They seem to be just inherited by the dependencies of PostgreSQL.
I'm not sure why libxml2 and libxslt are removed in the old commit f5ce6e0206ba3ba6593e6ac5dd13048ba95e9cb8 :(

Try to remove `pam-devel` and `readline-devel` ?

**Comment by amitlan** [comment]
I think the point of filtering out (as done by f5ce6e0206ba3ba6593e6ac5dd13048ba95e9cb8) seems to be avoid unnecessary build-time dependencies.  Especially, neither of libxml2 and libxslt are required by pg_rman in any way but `LIBS` inherited from postgresql-devel's makefile might have them.

For example, when the rpm `postgresql96-devel-9.6beta4-2PGDG.rhel6.x86_64.rpm` is installed, we have:
```
$ grep ^LIBS /usr/pgsql-9.6/lib/pgxs/src/Makefile.global 
LIBS = -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -ldl -lm 
LIBS := -lpgcommon -lpgport $(LIBS)
LIBS += -lws2_32
```
I guess that means we are implicitly building all these dependencies into pg_rman.  It's not immediately clear to me what they manifest as - will `gcc/ld` fail if it doesn't find `.so` or `.a` file for some library?  What if none of their symbol is referenced within `pg_rman.o`?  Won't `gcc/ld` complain?  I am trying to convince myself that it's not a big issue.

Moving on to the packaging consideration: It seems we need to declare build and install dependencies with `BuildRequires` and `Requires`, respectively, in the RPM spec file.  Currently we have:

```
$ grep Requires SPECS/pg_rman96.spec 
BuildRequires:  postgresql96-devel, zlib-devel
Requires:  postgresql96-libs
```

So only zlib-devel is pg_rman build dependency.  I wondered if libz should be a install dependency but I think it is required postgresql which is required by pg_rman.

**Comment by amitlan** [comment]
Removed the mention of `pam-devel` and `readline-devel` as required (5252c62c6a8dcb81d6473397a547c8ea2d9b7397).

**Comment by amitlan** [comment]
Just discovered that pg_rman builds fine with just `-lpq -lpgcommon -lpgport`, however the compiler is currently passed the following (given `/usr/pgsql-9.6/bin/pg_config`):

```
$ gcc <other-options-and-object-files>\
      -lpq -lpgcommon -lpgport \
      -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -ldl -lm \
      -o pg_rman
```

Of those that are essential, `libpgcommon` and `libpgport` are statically linked (there is no dynamic link option for them).  However, `libpq` is dynamically linked so it becomes an install dependency (and thus noted as Requires in pg_rman RPM spec file).

I am surprised that `-lz` can be safely dropped (`--with-zlib` or `--without-zlib`).  Hmm...
