### ISSUE TITLE
can pg_rman support output to stdout? 

### ISSUE THREAD

**Issue by digoal** [ossc-db/pg_rman#45]
HI, 
   if pg_rman can support backup output to stdout, people can do it with another tools together.
   for exp parallel compress tar.
   for exp streaming backup to another platform and do not need to write to local disk.
   
best regards.

**Comment by amitlan** [comment]
Hm, I assume you know that pg_rman is a base backup tool (like pg_basebackup and unlike pg_dump/pg_restore).

pg_rman writes backup files in a specialized format and maintains a backup catalog.  Also, various pg_rman commands depend on the backup file format and the catalog format.  So, I cannot see how a third-party tool could get involved in writing backups.

Could you elaborate your idea considering the above points?

**Comment by digoal** [comment]
HI, catalog can write to db or files, and backup sets can write to stdout or files.  
when local no space to store the backup sets , or when we must send the backup set to remote storage(like S3), we don't need store backup set to local disk.  if pg_rman support stdout, we can use pipe and send the backup set to other storage or platform.

**Comment by michaelpq** [comment]
This request looks difficult to me as pg_rman has little meaning to support tar mode per its backup file structure. I'd recommend just closing this ticket.

**Comment by digoal** [comment]
thank you.
