### ISSUE TITLE
Regression tests fail in master

### ISSUE THREAD

**Issue by bwtakacy** [ossc-db/pg_rman#57]
```
============== running regression test queries        ==============
test init                     ... ok
test option                   ... ok
test show                     ... ok
test delete                   ... FAILED
test purge                    ... ok
test backup                   ... ok
test backup_management        ... ok
test restore                  ... FAILED
test restore_checksum         ... FAILED
test backup_from_standby      ... ok
test arc_srv_log_management   ... ok
```

**Comment by amitlan** [comment]
I have seen that but didn't get time to figure out why yet.

**Comment by bwtakacy** [comment]
In my env, it is reproduced.

They seems to be timing issues and fixed by adding additional sleep or changing stop mode.
But I wonder why they comes to appear...
There might be something behavior change in PostgreSQL side.

About delete test,
```
*** /home/travis/build/ossc-db/pg_rman/pg_rman/expected/delete.out	2016-10-31 08:34:10.872764044 +0000
--- /home/travis/build/ossc-db/pg_rman/pg_rman/results/delete.out	2016-10-31 08:35:16.900764044 +0000
***************
*** 8,13 ****
  ###### DELETE COMMAND TEST-0002 ######
  ###### keep backups which are necessary for recovery ######
  try to delete before third backup
! 4
  1
  Number of deleted backups should be 1, is it so?: 1
--- 8,13 ----
  ###### DELETE COMMAND TEST-0002 ######
  ###### keep backups which are necessary for recovery ######
  try to delete before third backup
! 3
  1
  Number of deleted backups should be 1, is it so?: 1
```
this fails because the incremental backup or archive backup in the test script was not taken.

It can be avoided  by adding additional sleep before these backup.

```
diff --git a/sql/delete.sh b/sql/delete.sh
index 3a2e111..4a065f6 100644
--- a/sql/delete.sh
+++ b/sql/delete.sh
@@ -99,9 +99,11 @@ THIRD_BACKUP_DATE=`date +"%Y-%m-%d %H:%M:%S"`
 pg_rman backup -B ${BACKUP_PATH} -b incremental -Z -p ${TEST_PGPORT} -d postgres --quiet
 pg_rman validate -B ${BACKUP_PATH} --quiet
 pgbench -p ${TEST_PGPORT} >> ${TEST_BASE}/pgbench.log 2>&1
+sleep 2
 pg_rman backup -B ${BACKUP_PATH} -b archive -Z -p ${TEST_PGPORT} -d postgres --quiet
 pg_rman validate -B ${BACKUP_PATH} --quiet
 FOURTH_BACKUP_DATE=`date +"%Y-%m-%d %H:%M:%S"`
+sleep 2
 pg_rman backup -B ${BACKUP_PATH} -b full -Z -p ${TEST_PGPORT} -d postgres --quiet
 pg_rman validate -B ${BACKUP_PATH} --quiet
```

About backup_managent, restore, restore_checksum tests fail because the PostgreSQL server did not start after pg_rman restore in the test script.

I found that restore test can be passed by the below quick fix

```
diff --git a/sql/restore.sh b/sql/restore.sh
index badd024..6178957 100644
--- a/sql/restore.sh
+++ b/sql/restore.sh
@@ -164,6 +164,7 @@ pgbench -p ${TEST_PGPORT} -d pgbench > /dev/null 2>&1
 pg_rman backup -B ${BACKUP_PATH} -b archive -Z -p ${TEST_PGPORT} -d postgres --quiet;echo $?
 pg_rman validate -B ${BACKUP_PATH} --quiet
 psql --no-psqlrc -p ${TEST_PGPORT} -d pgbench -c "SELECT * FROM pgbench_branches;" > ${TEST_BASE}/T
+sleep 2
 pg_ctl stop -m immediate > /dev/null 2>&1
 pg_rman restore -B ${BACKUP_PATH} --quiet;echo $?
 pg_ctl start -w -t 600 > /dev/null 2>&1
@@ -222,7 +223,7 @@ pgbench -p ${TEST_PGPORT} pgbench > /dev/null 2>&1
 psql --no-psqlrc -p ${TEST_PGPORT} -d pgbench -c "SELECT * FROM pgbench_branches;" > ${TEST_BASE}/T
 TARGET_XID=`psql --no-psqlrc -p ${TEST_PGPORT} -d pgbench -tAq -c "INSERT INTO tbl0007 VALUES ('ins
 pgbench -p ${TEST_PGPORT} -d pgbench > /dev/null 2>&1
-pg_ctl stop -m immediate > /dev/null 2>&1
+pg_ctl stop -m fast > /dev/null 2>&1
 pg_rman restore -B ${BACKUP_PATH} --recovery-target-xid="${TARGET_XID}" --quiet;echo $?
 pg_ctl start -w -t 600 > /dev/null 2>&1
 psql --no-psqlrc -p ${TEST_PGPORT} -d pgbench -c "SELECT * FROM pgbench_branches;" > ${TEST_BASE}/T
@@ -245,7 +246,7 @@ pgbench -p ${TEST_PGPORT} pgbench > /dev/null 2>&1
 psql --no-psqlrc -p ${TEST_PGPORT} -d pgbench -c "SELECT * FROM pgbench_branches;" > ${TEST_BASE}/T
 TARGET_XID=`psql --no-psqlrc -p ${TEST_PGPORT} -d pgbench -tAq -c "INSERT INTO tbl0008 VALUES ('ins
 pgbench -p ${TEST_PGPORT} -d pgbench > /dev/null 2>&1
-pg_ctl stop -m immediate > /dev/null 2>&1
+pg_ctl stop -m fast > /dev/null 2>&1
 pg_rman restore -B ${BACKUP_PATH} --recovery-target-xid="${TARGET_XID}" --recovery-target-inclusive
 pg_ctl start -w -t 600 > /dev/null 2>&1
 psql --no-psqlrc -p ${TEST_PGPORT} -d pgbench -c "SELECT * FROM pgbench_branches;" > ${TEST_BASE}/T
@@ -266,7 +267,7 @@ pgbench -p ${TEST_PGPORT} -d pgbench > /dev/null 2>&1
 psql --no-psqlrc -p ${TEST_PGPORT} -d pgbench -c "SELECT * FROM pgbench_branches;" > ${TEST_BASE}/T
 pg_rman backup -B ${BACKUP_PATH} -b full -Z -p ${TEST_PGPORT} -d postgres --quiet;echo $?
 pg_rman validate -B ${BACKUP_PATH} --quiet
-pg_ctl stop -m immediate > /dev/null 2>&1
+pg_ctl stop -m fast > /dev/null 2>&1
 pg_rman restore -B ${BACKUP_PATH} --hard-copy --quiet;echo $?
 FLAGS=0
 for FILENAME in `ls ${ARCLOG_PATH}`
@@ -295,7 +296,7 @@ pg_rman backup -B ${BACKUP_PATH} -b incremental -Z -p ${TEST_PGPORT} -d postgres
 pg_rman validate -B ${BACKUP_PATH} --quiet
 pgbench -p ${TEST_PGPORT} -d db0010 >> ${TEST_BASE}/TEST-0010-db0010-init.out 2>&1
 psql --no-psqlrc -p ${TEST_PGPORT} -d db0010 -c "SELECT * FROM pgbench_branches;" > ${TEST_BASE}/TE
-pg_ctl stop -m immediate > /dev/null 2>&1
+pg_ctl stop -m fast > /dev/null 2>&1
 pg_rman restore -B ${BACKUP_PATH} --quiet;echo $?
 pg_ctl start -w -t 600 > /dev/null 2>&1
 psql --no-psqlrc -p ${TEST_PGPORT} -d db0010 -c "SELECT * FROM pgbench_branches;" > ${TEST_BASE}/TE
```

**Comment by amitlan** [comment]
Thanks for the analysis.

Here is a quick observation from the delete test:  Only in the master branch an ARCHIVE backup is skipped from the show command output (I added a line to sql/backup.sh to show backups before running the delete command)

This is with 9.6:
```
###### DELETE COMMAND TEST-0002 ######
###### keep backups which are necessary for recovery ######
==========================================================
 StartTime           Mode  Duration    Size   TLI  Status 
==========================================================
2016-11-01 12:00:06  FULL        0m  3489kB     1  OK
2016-11-01 12:00:04  ARCH        0m    26kB     1  OK
2016-11-01 12:00:02  INCR        0m    54kB     1  OK
2016-11-01 11:59:58  FULL        0m  5641kB     1  OK
2016-11-01 11:59:54  FULL        0m  5587kB     1  OK
try to delete before third backup
4
1
Number of deleted backups should be 1, is it so?: 1
```

With master:
```
###### DELETE COMMAND TEST-0002 ######
###### keep backups which are necessary for recovery ######
==========================================================
 StartTime           Mode  Duration    Size   TLI  Status 
==========================================================
2016-11-01 12:02:40  FULL        0m  3656kB     1  OK
2016-11-01 12:02:37  INCR        0m  1910kB     1  OK
2016-11-01 12:02:30  FULL        0m  7821kB     1  OK
2016-11-01 12:02:26  FULL        0m  7712kB     1  OK
try to delete before third backup
3
1
Number of deleted backups should be 1, is it so?: 1
```

I am wondering (looking for) why...

**Comment by amitlan** [comment]
I think I may have found something about the delete test.

In case of the missing ARCH backup with the master branch, all 10 of 10 WAL files processed are skipped, whereas in case of 9.6- servers, 10 of 11 files processed are skipped (behavior change of Postgres side I suppose).  Which means nothing is written to the backup in the former case; so it very quickly finishes, whereas at least 1 file is written in the latter case; at least some time is spent.

Now if another backup is taken immediately afterwards, the timestamp does not change from the above mentioned backup in almost all cases.  That means the new backup will overwrite the above backup and the latter will never be found.

**Comment by bwtakacy** [comment]
Wow, that's a quite surprise!
Thanks for your investigation.

> Now if another backup is taken immediately afterwards, the timestamp does not change from the above mentioned backup in almost all cases. That means the new backup will overwrite the above backup and the latter will never be found.

I have got to understand why additional sleep save the tests from failures.

**Comment by amitlan** [comment]
I also looked at some of the restore test failures.  Looking at the test 0004, it seems the reason for the server to fail to start:

Firstly, on immediate shutdown:
```
FATAL:  archive command was terminated by signal 3: Quit
DETAIL:  The failed archive command was: cp pg_wal/000000010000000000000004 /home/amit/pg_rman/results/restore/arclog/000000010000000000000004
LOG:  archiver process (PID 8342) exited with exit code 1
```

Then on start:
```
FATAL:  archive file "000000010000000000000004" has wrong size: 13697024 instead of 16777216
LOG:  startup process (PID 8419) exited with exit code 1
```

Changing the restore.sh script to use rsync instead of cp in archive_command made this issue disappear.  Hmm, interesting! Is it because rsync is atomic whereas cp is not?  Because the following is then seen in logs:

On immediate shutdown:
```
FATAL:  archive command was terminated by signal 3: Quit
DETAIL:  The failed archive command was: rsync pg_wal/000000010000000000000004 /home/amit/pg_rman/results/restore/arclog/000000010000000000000004
```

On start:
```
LOG:  redo starts at 0/3000028
LOG:  consistent recovery state reached at 0/30000F8
cp: cannot stat `/home/amit/pg_rman/results/restore/arclog/000000010000000000000004': No such file or directory
```

Note that WAL segment which was previously reported as incomplete (xxx0004) is not found at all.  But the test fails nevertheless because of the diff between before and after content of `select * from pgbench_branches`.  I am not sure how a "consistent recovery state" is reached without the missing segment but I think I may be missing something.

When I try test 0004 with 9.6, I get the following in logs:

On immediate shutdown:
```
LOG:  archiver process (PID 12261) exited with exit code 1
LOG:  database system is shut down
```

On start
```
LOG:  restored log file "000000010000000000000004" from archive
```

Note that the WAL segment xxx0004 exists without any damage and is restored.  We can say Postgres behavior has changed somehow with regard to archiving and immediate shutdown.  I didn't notice any such change in the commit log however.  In any case, adding `sleep 1` before immediate shutdown avoids the loss of xxx00004 segment, so fixes test 0004.

Test 0007 has a similar issue where there is a missing segment.  But in its case `sleep 1` does not help.  Instead like you suggested, fast shutdown trivially fixes the issue.  Similar thing going on with the tests 0008 and 0010;  same fix as test 0007.

One difference between test 0004 and others is that in case of the former, we take backup just before immediate shutdown, whereas in other cases we don't.  That somehow affects archiver activity differently for test 0004 than others.  Perhaps that's why sleep before immediate shutdown works as a fix only for 0004.

Sending a PR.

**Comment by bwtakacy** [comment]
Thanks for the PR, but it was failed as similar test failure.
I will rerun Travis CI and check it agagin.

Yeah, I have found that mysterious incomplete WAL file archiving causes the failure of PostgreSQL PITR in some test cases as you pointed out.
Very interesting.

I did not notice the rsync change the game.
Maybe the `test and cp` command as the PostgreSQL documentation tells also makes thing well.

**Comment by bwtakacy** [comment]
I have found the reason why the archive backup does not work.

In short, this is because the directory name change from `pg_xlog` to `pg_wal`.
So, there are several issues behind recent test failures.
One is the WAL directory renaming in the PostgreSQL side, and the others are timing issues in pg_rman test scripts.
Therefore, I think the test will be passed by combining  @amitlan patch in PR #59 and @atorik patch in PR #55.

#### Why the archive backup does not work with PG 10dev
In pg_rman archive backup, `wait_for_archive` tries to wait the WAL files contain the last XID to be archived, but fails as noted below.

This function use while loop and check the WAL archiving by `fileExists`.
Unfortunately, pg_rman pass the `pg_xlog` path for this.
```
1131 static void
1132 wait_for_archive(pgBackup *backup, const char *sql, int nParams,
1133                  const char **params)
1134 {
...(snip)...
1149     /* get filename from the result of pg_xlogfile_name_offset() */
1150     elog(DEBUG, "waiting for %s is archived", PQgetvalue(res, 0, 0));
1151     snprintf(ready_path, lengthof(ready_path),
1152         "%s/pg_xlog/archive_status/%s.ready", pgdata, PQgetvalue(res, 0, 0));    // HERE !!
...(snip)...
1163     /* wait until switched WAL is archived */
1164     try_count = 0;
1165     while (fileExists(ready_path))
1166     {
1167         sleep(1);
...(snip)...
````

The `fileExists` returns false because the path with `pg_xlog` already does not exists in PG 10.
This leads pg_rman not to wait the actual WAL archiving and incomplete backup.
```c
1327 /*
1328  * Return true if the path is a existing regular file.
1329  */
1330 bool
1331 fileExists(const char *path)
1332 {
1333     struct stat buf;
1334 
1335     if (stat(path, &buf) == -1 && errno == ENOENT)
1336         return false;
1337     else if (!S_ISREG(buf.st_mode))
1338         return false;
1339     else
1340         return true;
1341 }
```

**Comment by amitlan** [comment]
Aha, so we *do* need PR #58 before #59 

However, while any failures caused by pg_xlog->pg_wal change are understandable, I would still love to know the mystery behind all those timing issues.  Nevertheless, we should move ahead with the temporary workarounds.

**Comment by bwtakacy** [comment]
> However, while any failures caused by pg_xlog->pg_wal change are understandable, I would still love to know the mystery behind all those timing issues.

That's very important.
The current test script has a lot of points to be improved...

> Nevertheless, we should move ahead with the temporary workarounds.

Yeah!
It is more important to run the tests with PostgreSQL master branch HEAD.
Could you take this task?

Thanks,

**Comment by amitlan** [comment]
How about we just apply @atorik's PR #58 and rebase #59 to see if things improve?

**Comment by bwtakacy** [comment]
Sounds best!

**Comment by amitlan** [comment]
And done.  Everything seems fine for now.  Thanks for your help.
