### ISSUE TITLE
Tests fail on CentOS 6.8

### ISSUE THREAD

**Issue by wsdookadr** [ossc-db/pg_rman#62]
I ran `export PATH="$PATH:/usr/pgsql-9.5/bin/"` prior to building and pg_rman compiled succesfully.
I've used the `REL9_5_STABLE` branch in the git repository on CentOS 6.8
with PostgreSQL 9.5.5 installed from the official PostgreSQL packages.

below is the output of `make installcheck`

    [root@SERVER pg_rman]# make installcheck
    /usr/pgsql-9.5/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/pgsql-9.5/bin'    --dbname=contrib_regression init option show delete purge backup backup_management restore restore_checksum backup_from_standby arc_srv_log_management
    (using postmaster on Unix socket, default port)
    ============== dropping database "contrib_regression" ==============
    NOTICE:  database "contrib_regression" does not exist, skipping
    DROP DATABASE
    ============== creating database "contrib_regression" ==============
    CREATE DATABASE
    ALTER DATABASE
    ============== running regression test queries        ==============
    test init                     ... FAILED
    test option                   ... FAILED
    test show                     ... FAILED
    test delete                   ... FAILED
    test purge                    ... FAILED
    test backup                   ... FAILED
    test backup_management        ... FAILED
    test restore                  ... FAILED
    test restore_checksum         ... ok
    test backup_from_standby      ... FAILED
    test arc_srv_log_management   ... FAILED

    ========================
     10 of 11 tests failed. 
    ========================

    The differences that caused some tests to fail can be viewed in the
    file "/root/pg_rman/regression.diffs".  A copy of the test summary that you see
    above is saved in the file "/root/pg_rman/regression.out".

    make: *** [installcheck] Error 1

**Comment by bwtakacy** [comment]
Hi,

Could you show the `regression.diffs` and `regression.out` ?

**Comment by wsdookadr** [comment]
@bwtakacy sure:
- [regression.diffs](http://pastebin.com/RT5B3251)
- [regression.out](http://pastebin.com/yRxm7xCb)

**Comment by bwtakacy** [comment]
Thank you!

From the log files, the `initdb` command seems to fails in your environment.
Do you have something to think about?

The each test log files, `result/init.out`, `result/option.out`, and so on, contains more detail information. Are there any error about that?

**Comment by wsdookadr** [comment]
- [results/init.out](http://pastebin.com/XMers99d)
- [results/option.out](http://pastebin.com/CGZbLiaR)

**Comment by bwtakacy** [comment]
Hmm.

Could you apply the attached patch for your env and try again?

[analysis-patch.txt](https://github.com/ossc-db/pg_rman/files/670797/analysis-patch.txt)
To apply,  download the patch file and locate it in pg_rman directory and run the below command;

```
$ git apply analysis-patch.txt
```

or

```
$ patch -p1 < analysis-patch.txt
```

Then, `result/init/initdb.log` will be created.

**Comment by wsdookadr** [comment]
@bwtakacy ok, so `result/init/initdb.log` said that it `initdb` wasn't allowed to run as root.
I then unapplied the patch, re-ran everything as the user `postgres` user and all tests passed.
