### ISSUE TITLE
pg_rman does not work on 32bit Linux.

### ISSUE THREAD

**Issue by tomoki-t** [ossc-db/pg_rman#63]
pg_rman 1.3.3 does not work on my 32bit Linux box (Debian wheezy).
It seems that something is wrong with system identifier check.

$ pg_rman backup --backup-mode=full --debug
DEBUG: the initially configured target database : SYSTEM_IDENTIFIER = 3624381814
DEBUG: the system identifier of current target database : -670585482
ERROR: could not start backup
DETAIL: system identifier of target database is different from the one of initially configured database

Here is a quick workaround:
<pre>
diff -cr pg_rman-9_5_STABLE/backup.c pg_rman-9_5_STABLE_32bit/backup.c
*** pg_rman-9_5_STABLE/backup.c	2016-10-13 19:34:40.000000000 +0900
--- pg_rman-9_5_STABLE_32bit/backup.c	2016-12-27 10:58:27.642353547 +0900
***************
*** 880,886 ****
  	if(buffer != NULL)
  		result = (uint64) ((ControlFileData *) buffer)->system_identifier;
  	pg_free(buffer);
! 	elog(DEBUG, "the system identifier of current target database : %ld", result);
  	snprintf(sysident_str, sizeof(sysident_str), UINT64_FORMAT, result);
  
  	if ( strcmp(value, sysident_str) != 0)
--- 880,886 ----
  	if(buffer != NULL)
  		result = (uint64) ((ControlFileData *) buffer)->system_identifier;
  	pg_free(buffer);
! 	elog(DEBUG, "the system identifier of current target database : %llu", result);
  	snprintf(sysident_str, sizeof(sysident_str), UINT64_FORMAT, result);
  
  	if ( strcmp(value, sysident_str) != 0)
diff -cr pg_rman-9_5_STABLE/init.c pg_rman-9_5_STABLE_32bit/init.c
*** pg_rman-9_5_STABLE/init.c	2016-10-13 19:25:55.000000000 +0900
--- pg_rman-9_5_STABLE_32bit/init.c	2016-12-27 10:58:12.565725008 +0900
***************
*** 95,101 ****
  			(errcode(ERROR_SYSTEM),
  			 errmsg("could not create system identifier file: %s", strerror(errno))));
  	else
! 		fprintf(fp, "SYSTEM_IDENTIFIER='%lu'\n", sysid);
  
  	fclose(fp);
  
--- 95,101 ----
  			(errcode(ERROR_SYSTEM),
  			 errmsg("could not create system identifier file: %s", strerror(errno))));
  	else
! 		fprintf(fp, "SYSTEM_IDENTIFIER='%llu'\n", sysid);
  
  	fclose(fp);
  
</pre>

**Comment by bwtakacy** [comment]
Thank for reporting!

This is a definitely bug.
We will fix it.
