### ISSUE TITLE
postgresql GIN index  vaccum operation will be hang after pg_rman backup and restore

### ISSUE THREAD

**Issue by houjibofa** [ossc-db/pg_rman#66]
Hi,I test the postgresql GIN index with pg_rman. I find it will be hang after restore when I execute the vacuum command. The detailinformation is in http://www.postgresql-archive.org/GIN-index-vacuum-hang-after-pg-rman-restore-in-PG9-2-21-td5966975.html.

**Comment by amitlan** [comment]
Thanks for reporting here.

I think it might be a pg_rman bug.  GIN index page format is somewhat different from what pg_rman thinks. So pg_rman's backup-space-saving optimization overwrites some important metadata in GIN index page with zeros.

Will try to fix this by avoiding the optimization for GIN index files.

**Comment by amitlan** [comment]
Has been fixed in 1.3.5 release.
