### ISSUE TITLE
Bug:Some deleted data was restored when execute in a special way.

### ISSUE THREAD

**Issue by lchch** [ossc-db/pg_rman#72]
Here is the example：
```
highgo=# create table t2(i int,j int,k varchar);
CREATE TABLE
highgo=# insert into t2 (i,j,k) select generate_series(1,200),1,getrandomstring(20)
INSERT 0 200
highgo=# select pg_size_pretty(pg_relation_size('t2'));
 pg_size_pretty 
----------------
 16 kB
(1 row)
```
**THEN DO FULL BACKUP→pg_rman backup -b full**
```
highgo=# delete from t2 where i > 99;
DELETE 101
highgo=# vacuum ;
VACUUM
highgo=# select count(*) from t2;
 count 
-------
    99
(1 row)
highgo=# select pg_size_pretty(pg_relation_size('t2'));
 pg_size_pretty 
----------------
 8192 bytes
(1 row)
```
**THEN DO INCREMENT BACKUP→pg_rman backup -b increment**
Suppose that the time now is '2018-02-26 13:13:06'
**THEN DO RESTORE→pg_rman restore --recovery-target-time '2018-02-26 13:13:06'**
Here is the result of restore.
```
highgo=# select count(*) from t2;
 count 
-------
   142
(1 row)

highgo=# select pg_size_pretty(pg_relation_size('t2'));
 pg_size_pretty 
----------------
 16 kB
(1 row)
```
Now is the bug that a lot of deteted data is relived.

I read the source code,and find:
In pg code:
If the last datafile pages  of a table has nothing usable tuples,
then the pages will be purged with a vacuum command. 
In pg_rman code:
You does not mental this conditions that nums of page of a relation reduced via vacuum.

My english is so bad,maybe what I describe is not very clear,beg your pardon.

**Comment by atorik** [comment]
Ichch,

Sorry for late reply and thanks for reporting.

As you mention, I think it's a design bug of pg_rman.
I've written a patch for this issue(#75), so if you have time, please test it.

**Comment by atorik** [comment]
Merged PR for this issue.
