### ISSUE TITLE
BUG:A scene that maybe backup failed.

### ISSUE THREAD

**Issue by lchch** [ossc-db/pg_rman#73]
If user has created tablespace to 'data/pg_tbspc' dir.
Then can not complete the backup.

**Comment by atorik** [comment]
Did you really create tablespace  'to' data/pg_tbspc, meaning LOCATION = 'data/pg_tblspc'?

PostgreSQL does not recommend creating tablespace in its database cluster and you would see a warning message like below.

```
  WARNING:  tablespace location should not be inside the data directory 
```

**Comment by lchch** [comment]
PG code just give a 'Warning' with create tablespace success,and that cause backup failed,so i think it may be not so good.
If you think it is OK, then we can close it.

**Comment by atorik** [comment]
I think creating tablespace under pgdata is less meaningful.
Usually, tablespace is used when people do NOT want to put some data under pgdata for reasons like disk space limitation or performance.

We're not going to dive into this issue further more now.

**Comment by lchch** [comment]
Ok,I can close it now.
