### ISSUE TITLE
ERROR: could not open destination file … No such file or directory

### ISSUE THREAD

**Issue by mknecht** [ossc-db/pg_rman#9]
Hey, I am running Postgres 9.4, built pg_rman with the respective branch, inited the archive dir, and was trying to create a first, full backup. I got this instead:

    $ /usr/lib/postgresql/9.4/bin/pg_rman backup -b full  -B /var/lib/postgresql/archives/ -D /var/lib/postgresql/data/
    INFO: copying database files
    INFO: copying archived WAL files
    ERROR: could not open destination file "/var/lib/postgresql/archives//20150914/082537/arclog/20150914/082423/database/pg_clog/0000": No such file or directory

pg_rman definitely has write access, as it created a lot of files and directories already, and `show` lists the backup in ERROR state. Anything I am missing?

**Comment by bwtakacy** [comment]
Hmm, seems to something wrong.

From messages, pg_rman caused ERROR in copying archived WAL files but failed in trying to access database file.

Where did you set ARCLOG_PATH? 
This can be confirmed by `cat /var/lib/postgresql/archives/pg_rman.ini` in your environment.
Pg_rman requires ARCLOG_PATH set to path of archived WAL files in pg_rman.ini or given with command line option `-A` in `pg_rman backup`.

**Comment by mknecht** [comment]
I initialized the catalog as follows:

    /usr/lib/postgresql/9.4/bin/pg_rman init  -B /var/lib/postgresql/backups -A /var/lib/postgresql/archives/ -D /var/lib/postgresql/data/

I confirmed that the archive path in the backup catalog is the correct one (/var/lib/postgresql/archives/). Then, running the following command produces the error:

    /usr/lib/postgresql/9.4/bin/pg_rman backup -b full  -B /var/lib/postgresql/backups -D  /var/lib/postgresql/data/
    INFO: copying database files
    INFO: copying archived WAL files
    ERROR: could not open destination file "/var/lib/postgresql/backups/20150915/005127/arclog/20150914/082423/database/pg_clog/0000": No such file or directory

(In the initial post I accidentally set arclog and backup path to the same dir. I corrected this by initializing a new, separate backup catalog as above, and got the same error, so the issue still stands.)

**Comment by amitlan** [comment]
It's not really clear to me yet what's going on here but it may be interesting to see that the erroneous portion of the failing path viz. `20150914/082423/database/pg_clog/0000` is the same in both your posts. It's possible that it's coming from some old catalog. But what's more serious is that it's suffixing arclog path at all.

Also, it has come to my notice that pg_rman keeps using any existing values of the environment variables `PGDATA` and `BACKUP_PATH` even after performing `pg_rman init` with newer values using `-A` and `-B`. Haven't concluded yet though that that may be behind the reported issue or it may not be at all.

**Comment by amitlan** [comment]
It's not really clear to me yet what's going on here but it may be interesting to see that the erroneous portion of the failing path viz. 20150914/082423/database/pg_clog/0000 is the same in both your posts. It's possible that it's coming from some old catalog. But what's more serious is that it's suffixing arclog path at all.

**Comment by bwtakacy** [comment]
In archive WAL backup, pg_rman checks old files in the past backup. The error message said that pg_rman still found past backup taken at 2015/09/15 00:51:27 and this backup contains corrupt files. I guess this corruption is caused by setting arclog and backup path to the same directory.

So I think the simplest way to recover is doing `rm -rf /var/lib/postgresql/backups/*` and starting from `pg_rman init` again.

**Comment by amitlan** [comment]
I think `2015/09/15 00:51:2` is ID of the backup being taken.

He mentioned that even after realizing the mistake of using the same directory as both `ARCLOG_PATH` and `BACKUP_PATH` and fixing it, the issue still persists.

Moreover, doesn't it feel odd that such a path name as shown in the error message is generated at all? That could be a bug, something like stack frame corruption? Just wondering...

**Comment by amitlan** [comment]
@mknecht meanwhile, output with `--debug` may be helpful

**Comment by amitlan** [comment]
Okay, reproduced this. There's no bug as such as I suspected in my last message.

```
$ pg_rman backup -b full -d postgres -A $BACKUP_PATH
INFO: copying database files
NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
INFO: copying archived WAL files
ERROR: could not open destination file "/tmp/bkp/20150915/175009/arclog/20150915/175009/database/pg_clog/0000": No such file or directory
```

You can see here that the trigger is to specify `BACKUP_PATH` where `ARCLOG_PATH` (`-A`) is expected.

With that said, I am not sure what went wrong in @mknecht 's seconds attempt.
